### ISSUE TITLE
Libtool should be a dependency.

### ISSUE THREAD

**Issue by nixcamic** [kiwix/kiwix-build#152]
After following the instructions in the readme everything went fine except for the following error I recieved during libaria2 post_prepare_script: 

```
configure.ac:40: installing './missing'
Makefile.am: installing './INSTALL'
lib/Makefile.am:30: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:30:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:30:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:30:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:30:   its definition is in aclocal's search path.
lib/Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
```

running "sudo apt install libtool" solved it.

**Comment by kelson42** [comment]
@nixcamic I'm not sure about what you mean... What is the list of command you run? Is that not a bug of aria2 configuration scripts?

**Comment by kelson42** [comment]
We have too few details about the command, the system on which it runs, etc. Please complete and reopen.
