### ISSUE TITLE
https://download.openzim.org/nightly/ is empty!

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#156]
It should not, openzim nightlies are still written to kiwix.download.kiwix.org

**Comment by mgautierfr** [comment]
Kiwix-build now publish to the right directory.
However, it assume the directory exists (as it does for kiwix-* project)

Can you update the cron on the server to create the `download.openzim.org/nightly/<date>` directory ?

**Comment by mgautierfr** [comment]
Fixed with #168
