### ISSUE TITLE
Static build failing

### ISSUE THREAD

**Issue by swiftugandan** [kiwix/kiwix-build#159]
I run `kiwix-build --force-install-packages --target-platform native_static kiwix-tools` on ubuntu 16.04 but it failed with the log below. Please help

<pre>
build kiwix-tools :
  configure kiwix-tools : SKIP
  compile kiwix-tools : ERROR
[1/6] /tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/bin/kiwix-compile-resources --cxxfile static/server/server-resources.cpp --hfile static/server/server-resources.h ../../SOURCE/kiwix-tools/static/server/resources_list.txt
[2/6] ccache c++  -o src/installer/kiwix-install 'src/installer/kiwix-install@exe/kiwix-install.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
[3/6] ccache c++  -o src/manager/kiwix-manage 'src/manager/kiwix-manage@exe/kiwix-manage.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
jquery-ui/jquery-ui.structure.min.css ['jquery_ui', 'jquery_ui_structure_min_css']
jquery-ui/jquery-ui.min.js ['jquery_ui', 'jquery_ui_min_js']
jquery-ui/external/jquery/jquery.js ['jquery_ui', 'external', 'jquery', 'jquery_js']
jquery-ui/images/ui-bg_flat_0_aaaaaa_40x100.png ['jquery_ui', 'images', 'ui_bg_flat_0_aaaaaa_40x100_png']
jquery-ui/images/ui-bg_flat_75_ffffff_40x100.png ['jquery_ui', 'images', 'ui_bg_flat_75_ffffff_40x100_png']
jquery-ui/images/ui-icons_222222_256x240.png ['jquery_ui', 'images', 'ui_icons_222222_256x240_png']
jquery-ui/images/ui-bg_glass_55_fbf9ee_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_55_fbf9ee_1x400_png']
jquery-ui/images/ui-bg_highlight-soft_75_cccccc_1x100.png ['jquery_ui', 'images', 'ui_bg_highlight_soft_75_cccccc_1x100_png']
jquery-ui/images/ui-bg_glass_65_ffffff_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_65_ffffff_1x400_png']
jquery-ui/images/ui-icons_2e83ff_256x240.png ['jquery_ui', 'images', 'ui_icons_2e83ff_256x240_png']
jquery-ui/images/ui-icons_cd0a0a_256x240.png ['jquery_ui', 'images', 'ui_icons_cd0a0a_256x240_png']
jquery-ui/images/ui-icons_888888_256x240.png ['jquery_ui', 'images', 'ui_icons_888888_256x240_png']
jquery-ui/images/ui-bg_glass_75_e6e6e6_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_75_e6e6e6_1x400_png']
jquery-ui/images/animated-overlay.gif ['jquery_ui', 'images', 'animated_overlay_gif']
jquery-ui/images/ui-bg_glass_75_dadada_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_75_dadada_1x400_png']
jquery-ui/images/ui-icons_454545_256x240.png ['jquery_ui', 'images', 'ui_icons_454545_256x240_png']
jquery-ui/images/ui-bg_glass_95_fef1ec_1x400.png ['jquery_ui', 'images', 'ui_bg_glass_95_fef1ec_1x400_png']
jquery-ui/jquery-ui.theme.min.css ['jquery_ui', 'jquery_ui_theme_min_css']
jquery-ui/jquery-ui.min.css ['jquery_ui', 'jquery_ui_min_css']
home.html.tmpl ['home_html_tmpl']
include.html.part ['include_html_part']
taskbar.css ['taskbar_css']
taskbar.html.part ['taskbar_html_part']
global_taskbar.html.part ['global_taskbar_html_part']
[4/6] ccache c++  -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include/ -I/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' -MF 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o.d' -o 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' -c static/server/server-resources.cpp
[5/6] ccache c++  -Isrc/server/kiwix-serve@exe -Isrc/server -I../../SOURCE/kiwix-tools/src/server -Istatic/server -I/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include/ -I/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -std=c++11 -O0 -g -pthread -MMD -MQ 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -MF 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o.d' -o 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' -c ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp: In function ‘MHD_Response* build_response(const void*, unsigned int, const string&, const string&, bool, bool)’:
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:221:35: warning: ‘MHD_Response* MHD_create_response_from_data(size_t, void*, int, int)’ is deprecated: MHD_create_response_from_data() is deprecated, use MHD_create_response_from_buffer() [-Wdeprecated-declarations]
   struct MHD_Response* response = MHD_create_response_from_data(
                                   ^
In file included from ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:77:0:
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include/microhttpd.h:2034:1: note: declared here
 MHD_create_response_from_data (size_t size,
 ^
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:221:35: warning: ‘MHD_Response* MHD_create_response_from_data(size_t, void*, int, int)’ is deprecated: MHD_create_response_from_data() is deprecated, use MHD_create_response_from_buffer() [-Wdeprecated-declarations]
   struct MHD_Response* response = MHD_create_response_from_data(
                                   ^
In file included from ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:77:0:
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include/microhttpd.h:2034:1: note: declared here
 MHD_create_response_from_data (size_t size,
 ^
../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:222:44: warning: ‘MHD_Response* MHD_create_response_from_data(size_t, void*, int, int)’ is deprecated: MHD_create_response_from_data() is deprecated, use MHD_create_response_from_buffer() [-Wdeprecated-declarations]
       length, const_cast<void*>(data), MHD_NO, MHD_YES);
                                            ^
In file included from ../../SOURCE/kiwix-tools/src/server/kiwix-serve.cpp:77:0:
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/include/microhttpd.h:2034:1: note: declared here
 MHD_create_response_from_data (size_t size,
 ^
[6/6] ccache c++  -o src/server/kiwix-serve 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' 'src/server/kiwix-serve@exe/request_context.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
FAILED: ccache c++  -o src/installer/kiwix-install 'src/installer/kiwix-install@exe/kiwix-install.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(util.o): In function `aria2::util::getHomeDir[abi:cxx11]()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/util.cc:1406: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(SocketCore.o): In function `aria2::callGetaddrinfo(addrinfo**, char const*, char const*, int, int, int, int)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/SocketCore.cc:1446: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::Sqlite3CookieParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:56: undefined reference to `sqlite3_open_v2'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:64: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::parse()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:149: undefined reference to `sqlite3_exec'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:153: undefined reference to `sqlite3_free'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseUpdate(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:161: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseFinal(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:175: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::reset()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:188: undefined reference to `xmlCtxtResetPush'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::XmlParser(aria2::ParserStateMachine*)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:148: undefined reference to `xmlCreatePushParserCtxt'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::~XmlParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:154: undefined reference to `xmlFreeParserCtxt'
collect2: error: ld returned 1 exit status
FAILED: ccache c++  -o src/server/kiwix-serve 'src/server/kiwix-serve@exe/meson-generated_.._.._.._static_server_server-resources.cpp.o' 'src/server/kiwix-serve@exe/kiwix-serve.cpp.o' 'src/server/kiwix-serve@exe/request_context.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(util.o): In function `aria2::util::getHomeDir[abi:cxx11]()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/util.cc:1406: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(SocketCore.o): In function `aria2::callGetaddrinfo(addrinfo**, char const*, char const*, int, int, int, int)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/SocketCore.cc:1446: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::Sqlite3CookieParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:56: undefined reference to `sqlite3_open_v2'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:64: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::parse()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:149: undefined reference to `sqlite3_exec'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:153: undefined reference to `sqlite3_free'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseUpdate(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:161: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseFinal(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:175: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::reset()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:188: undefined reference to `xmlCtxtResetPush'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::XmlParser(aria2::ParserStateMachine*)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:148: undefined reference to `xmlCreatePushParserCtxt'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::~XmlParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:154: undefined reference to `xmlFreeParserCtxt'
collect2: error: ld returned 1 exit status
FAILED: ccache c++  -o src/manager/kiwix-manage 'src/manager/kiwix-manage@exe/kiwix-manage.cpp.o' -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--no-undefined -Wl,--as-needed -static-libstdc++ --static -pthread -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib64 -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -Wl,--start-group -lkiwix -lctpp2 -lzim -llzma -pthread -lz -licui18n -licuuc -licudata -lpthread -lm -lpugixml -laria2 -lxapian -lrt -Wl,--end-group -lz -luuid -L/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu -lmicrohttpd -lz -lrt -Wl,-rpath,XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX -Wl,-rpath-link,  
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(util.o): In function `aria2::util::getHomeDir[abi:cxx11]()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/util.cc:1406: warning: Using 'getpwuid' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(SocketCore.o): In function `aria2::callGetaddrinfo(addrinfo**, char const*, char const*, int, int, int, int)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/SocketCore.cc:1446: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::Sqlite3CookieParser(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:56: undefined reference to `sqlite3_open_v2'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:64: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::parse()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:149: undefined reference to `sqlite3_exec'
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:153: undefined reference to `sqlite3_free'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Sqlite3CookieParser.o): In function `aria2::Sqlite3CookieParser::~Sqlite3CookieParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Sqlite3CookieParser.cc:69: undefined reference to `sqlite3_close'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseUpdate(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:161: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::parseFinal(char const*, unsigned long)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:175: undefined reference to `xmlParseChunk'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::reset()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:188: undefined reference to `xmlCtxtResetPush'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::XmlParser(aria2::ParserStateMachine*)':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:148: undefined reference to `xmlCreatePushParserCtxt'
/tmp/kiwix/kiwix-build/BUILD_native_static/INSTALL/lib/x86_64-linux-gnu/libaria2.a(Xml2XmlParser.o): In function `aria2::xml::XmlParser::~XmlParser()':
/tmp/kiwix/kiwix-build/SOURCE/libaria2-1.33.1/src/Xml2XmlParser.cc:154: undefined reference to `xmlFreeParserCtxt'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
run command 'ninja -v'
current directory is '/tmp/kiwix/kiwix-build/BUILD_native_static/kiwix-tools'
</pre>

**Comment by mgautierfr** [comment]
I've just fix this with this commit https://github.com/kiwix/kiwix-build/pull/157/commits/9f877180dfa5809c0c122a26c3e9b13146fca1e2

Please:
- update to last version of kiwix-build master
- reinstall it (`pip install --upgrade .`)
- remove directory `BUILD_native_static`
- relaunch `kiwix-build --target-platform native_static kiwix-tools`
