### ISSUE TITLE
libtool build dep missing

### ISSUE THREAD

**Issue by danboid** [kiwix/kiwix-build#169]
I have just tried to build the latest git version of kiwix under Ubuntu 18.04. My first attempt failed with an error like this:

```
~/src/kiwix-build$ kiwix-build 
[INSTALL PACKAGES]
SKIP
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  svncheckout icu4c : SKIP
  svnupdate icu4c : SKIP
  patch icu4c : SKIP
prepare sources libzim :
  gitclone libzim : SKIP
  gitupdate libzim : OK
prepare sources libaria2 :
  download libaria2 : SKIP
  extract libaria2 : SKIP
  patch libaria2 : SKIP
  post_prepare_script libaria2 : ERROR
lib/Makefile.am:30: error: Libtool library used but 'LIBTOOL' is undefined
lib/Makefile.am:30:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
lib/Makefile.am:30:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
lib/Makefile.am:30:   If 'LT_INIT' is in 'configure.ac', make sure
lib/Makefile.am:30:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1
run command 'autoreconf -i'
...
```

The solution is not to run autoreconf as it suggests but to install the libtool package. This would ideally be done for you by the kiwix-build script.

**Comment by kelson42** [comment]
@danboid Do you have installed the package `libtool` installed?

**Comment by danboid** [comment]
I didn't have libtool installed previously but when kiwix-build failed, I installed it. That enabled kiwix to build successfully.

Does kiwix-build not support building Debian packages yet?

**Comment by kelson42** [comment]
@danboid indeed... packaging effort runs at Debian level to package our softwares.

**Comment by kelson42** [comment]
@mgautierfr May you please do the necessary to make the "libtool" dependency problem fixed - or at least properly documented?

**Comment by danboid** [comment]
Thanks @mgautierfr  and @kelson42 !
