### ISSUE TITLE
Compile Xapian with --disable-backend-remote

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#179]
This should reduce a bit the size of the library and of course we do not need this backend in Kiwix. This was not possible in the past because a bug in Xapian, but this has been fixed in Xapian 1.4.6. More details https://trac.xapian.org/ticket/361

**Comment by mgautierfr** [comment]
The last official xapian version is still 1.4.5 (https://xapian.org/download).
But yes, I agree with the idea when 1.4.6 will be released.
