### ISSUE TITLE
Readme build steps for android don't work anymore

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-build#217]
```kiwix-build kiwix-android --android-arch arm``` works but ```kiwix-build kiwix-android --target-platform android_arm``` doesn't

**Comment by mgautierfr** [comment]
As said in the README :
```
But, kiwix-android apk can also be multi arch (ie, it includes kiwix-lib for several architectures). To do so, you must ask to build kiwix-android using the android platform:
```

Ok, there is typo in the line just before in the readme it should be 
```
$ kiwix-build **kiwix-lib** --target-platform android_arm
```
But the readme explicitly said you should use `android` platform, not `android_arm`.
