### ISSUE TITLE
Dependence between kiwix and openzim.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#22]
The recent PR #21 allow `kiwix-build` to build the `zimwriterfs` project.
This add no extra dependencies between the kiwix projects and `zimwriterfs`. It just said to `kiwix-build` how to build `zimwriterfs`.

This PR leads to a discussion between @kelson42 and me about what is the difference between the two organization openzim and kiwix.
I will try to be objective here, but I may not succeed, I'm part of the discussion. @kelson42, do not hesitate to correct or complete me.

The main argument of @kelson42 is that the openzim and kiwix are two different projects and must stay as it. People should be able to use zim (through `zimlib`, `zimwriterfs` or any other tools) without using at all kiwix or kiwix-related projects. Thus, he asks me to think of how we could separate the two projects and do not add `zimwriterfs` to `kiwix-build`. (But we agree that for now, it worth to accept the PR as we could easily remove `zimwriterfs` or split/duplicate `kiwix-build` if necessary)

I globally agree with this will. The zim format is a (somehow advanced) archive format and should stay as it. Kiwix is a application that use the zim format to store and display web content (mainly mediawiki content, but not only)

But, saying that, I don't see why the kiwix team couldn't have tools to use and compile `zimwriterfs`.
We already have tool to compile other dependencies as `xapian`, `pugixml`, .. and `zimlib`.
`zimwriterfs` is not intended to be used by kiwix end user, but I don't see why we (kiwix) should avoid publish a tool to compile it. If someone asks about it, we just could answer «At kiwix, we build zimwriterfs this way. It simpler this way, but do as you want. Use it, or not, we don't care.»
We already greatly use `zimlib` (kiwix/kiwix-lib and thus kiwix/kiwix-tools, kiwix/kiwix-android, kiwix/kiwix-IOS, kiwix/node-libzim)  and `zimwriterfs` (kiwix/mwoffliner, kiwix/sotoki, kiwix/phet, kiwix/youtube, kiwix/TED, kiwix/gutemberg). And I'm not aware of other projects using libzim.

The other solutions are to duplicate `kiwix-build` or move `kiwix-build` to a generic and independent builder. And I'm appealing by none of them.

**Comment by kelson42** [comment]
A bit of time went on... Now it seems to me that even if the situation is not perfect, the best solution is simply to keep the current solution and let kiwix-build compiling easily and publishing nightlies. Of course that does not mean that the compilation script and documentation of openZIM project should be weak. So my opinion is made: we stick to the current solution and close the ticket.

**Comment by kelson42** [comment]
This is what we do now :) Problem finally solved.
