### ISSUE TITLE
Pls. add links and information about ZIM download file checksums

### ISSUE THREAD

**Issue by Wikinaut** [kiwix/kiwix-build#237]
I am desperately seeking for the checksum files of the ZIM files in the download area https://download.kiwix.org/zim/ .

I remember to have seen a page for each file, but the server is not listing these files on https://download.kiwix.org/zim/ , and the FAQ http://wiki.kiwix.org/wiki/FAQ is silent about checksums.

**Comment by kelson42** [comment]
Solution has been added in the FAQ http://wiki.kiwix.org/wiki/FAQ

**Comment by Menjuel** [comment]
The website FAQ (not the wiki) still lists an old location of the SHAs as being located here https://lb.download.kiwix.org/zim/[name_of_file.sha256] which is not the case anymore. Instead the FAQ on the wiki lists them here 
https://download.kiwix.org/zim/wikipedia/[name_of_file.zim.mirrorlist which is correct.

**Comment by kelson42** [comment]
@rgaudin Do you understand where that is exactly?

**Comment by rgaudin** [comment]
No, I've not been able to find this on the website FAQ or troubleshooting. @Menjuel can you share the URL?

The Wiki is mostly obsolete (https://github.com/kiwix/web/issues/238). [downloads](https://github.com/kiwix/operations/wiki/Downloads) has all the details
