### ISSUE TITLE
Provide library.xml as json file

### ISSUE THREAD

**Issue by sharun-s** [kiwix/kiwix-build#240]
Not sure if this is the right repo for this issue. I am looking for where/how library.xml is being generated.

I am trying to add a button in kiwix-js that allows users to update the local catalog of zim's from http://download.kiwix.org/library/library.xml

The issue with downloading the xml file from javascript (xhr) is I get a same-origin violation. The request would work if it was json - First and second answer explain why - https://stackoverflow.com/questions/8389440/

Currently the user has to run a python script outside the browser to download xml/convert to json/update the webapp source code etc which is messy. I would like to simplify this to all happen within javascript.  

Also (maybe this needs to be a separate issue/question), the xml has a meta4 links. How do the direct/bitorrent links get generated on the kiwix main page? Basically I want to provide that list within kiwix-js. There is probably some reusable code there.

**Comment by kelson42** [comment]
library.xml has no future, OPDS backend has http://wiki.kiwix.org/wiki/OPDS

**Comment by sharun-s** [comment]
Thank! Will use that.

**Comment by sharun-s** [comment]
I just tested it and implemented a link update mech on my branch. It works. Looks like the CORS setting for the root.xml allows it to be downloaded unlike the library.xml
