### ISSUE TITLE
Libkiwix release process should publish libkiwix JNI artefact to JFrog bintray

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#257]
Kiwix for Android should rely/relies on a specific version of the libkiwix JNI based artefact. This artefact is stored in the artefact library "JFrog Bintray".

Currently, a version the libkiwix (does not have to be an officially tagged libkiwix version) is uploaded time to time by @mhutti manually to JFrog. This generates the following problems:
* This version is compiled on his computer
* This version so far does not stick to an official release/version and we do not really know what it is
* It does not have an easy way to know to which commit of the code is was done.

We need to be more rigorous on this and have this artefact library being updated only with official new release via Travis-ci. That means the libkiwix release mgmt should push the binary stuff to JFrog Bintray

**Comment by kelson42** [comment]
@mhutti1 Please explain to @mgautierfr how to do that.

**Comment by mhutti1** [comment]
I currently copy the contents of the built kiwix lib directory into a pre generated android module that can then be uploaded with a simple gradle command. Will need to think about how best to do this with our build setup though / where this pre generated module should live.

**Comment by kelson42** [comment]
This will be fixed with https://github.com/kiwix/kiwix-lib/pull/231

**Comment by kelson42** [comment]
Duplicate of  kiwix/kiwix-android#489
