### ISSUE TITLE
CI old nighlies should be cleaned

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#267]
On the old download serveur with had these cron entries:
```
0 0 * * * find /var/www/download.kiwix.org/nightly/ -mindepth 1 -maxdepth 1 -type d -mtime +30 -exec rm -rf {} \;
0 0 * * * find /var/www/download.openzim.org/nightly/ -mindepth 1 -maxdepth 1 -type d -mtime +30 -exec rm -rf {} \;
```

I think meanwhile that this is the responsability of the CI to make cleaning of his own files... so running a similar command after each new upload of nightlies.

**Comment by kelson42** [comment]
This has been done

**Comment by mgautierfr** [comment]
> This has been done

Where ?
I somehow disagree with the idea of having kiwix-build cleaning the nightlies.
There are several scripts that publish daily, there should not be one of them to clean all.
Cron is easy to setup, why move this else where where it would be more difficult to implement ?

**Comment by kelson42** [comment]
@mgautierfr This is done outside the kiwix-build, in the download.kiwix.org Docker container, see https://github.com/kiwix/maintenance/commit/c89e0576bca57388e9bb921df80f249578cc3c49
