### ISSUE TITLE
New flatpack filename is really not fancy

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#272]
`org.kiwix.Client.2018-11-30.flatpak `, I hope we can do better.

**Comment by mgautierfr** [comment]
What do you propose ?

**Comment by mgautierfr** [comment]
`org.kiwix.Client` comes from the standard "reverse dns" format.
This is needed in a lot of place :
- Desktop entry file : https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#file-naming
- App stream : https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#sect-Metadata-GenericComponent
- Flatpak : http://docs.flatpak.org/en/latest/conventions.html

I thought it was just an "hidden" identifier, but the recommendation is to have the desktop file named with the appid. In the flathub submission review (https://github.com/flathub/flathub/pull/768#discussion_r240983296) it is asked to rename it.

As I agree that `org.kiwix.Client` is not the more explicit name we could have for the user. Can (should?) we find another name (before flathub accept it) ?

- org.kiwix.Desktop
- org.kiwix.Viewer
- other ?

**Comment by kelson42** [comment]
Thank you for the explanation. `org.kiwix.desktop` lowercase would be possible? otherwise `org.kiwix.Desktop` looks good.

**Comment by kelson42** [comment]
New name looks like `org.kiwix.desktop.2.0-beta2.flatpak`. Looks good to me.
