### ISSUE TITLE
Building on small systems like RaspberryPI etc

### ISSUE THREAD

**Issue by jamesfrances** [kiwix/kiwix-build#279]
When you build this on a small system it quite oftens dies because it creates too many gcc processes and fills the memory/cpu. Then it just swaps to death or you get "-bash: fork: retry: Resource temporarily unavailable" errors.

Is there anyway of reducing this ? 

I've tried export MAKEFLAGS=' -j3 ' but that doesnt seem to work.

Thanks in advance

**Comment by kelson42** [comment]
@jamesfrances What do you want to build exactly?

**Comment by jamesfrances** [comment]
I'm just doing a kiwix-build native_dyn so nothing really special.

It will build eventually, but it generally takes a few reboots to get it done because the kiwix-build process will start up to 7 or 8 gcc processes that kill the system.

**Comment by kelson42** [comment]
@mgautierfr feedback?

**Comment by jamesfrances** [comment]
I have just built it again and it seems to work first time with hammering the system.

Thanks - JF

**Comment by kelson42** [comment]
@jamesfrances nice. Thx for the feedback.
