### ISSUE TITLE
macOS: error when build kiwix-lib natively

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#29]
Using code from branch `apple-platforms`, building on macOS natively, encountered errors when building kiwix-lib. Please see log for detail.
[log.txt](https://github.com/kiwix/kiwix-build/files/914384/log.txt)

**Comment by kelson42** [comment]
@mgautierfr Any clue?

**Comment by mgautierfr** [comment]
@automactic, can you try with the macos branch of kiwix-lib (https://github.com/kiwix/kiwix-lib/tree/macos) ?

To do so, you can use this commit https://github.com/kiwix/kiwix-build/commit/aa1b97f2525c2e57833abce8316721bc77dc87e5 (or add the line yourself in kiwix-build)
Delete `SOURCE/kiwix-lib` to be sure kiwix-build get the last source and relaunch kiwix-build with same options.

**Comment by automactic** [comment]
@mgautierfr I have modified my code as described. Now I have issue `Dependency 'icu-i18n' not found` when building kiwix-lib.

**Comment by mgautierfr** [comment]
@automactic, can you give me the icu compilation logs ? (`BUILD_native_dyn/LOGS/cmd_*_icu4c.log` files)

What is the content of directories `BUILD_native_dyn/INSTALL/lib/pkgconfig` and `BUILD_native_dyn/INSTALL/lib64/pkgconfig` ? (If they exist)

**Comment by automactic** [comment]
- Logs: [logs.zip](https://github.com/kiwix/kiwix-build/files/1058126/logs.zip)
- Content of .../lib/pkgconfig: 
![screenshot 2017-06-07 09 35 18](https://user-images.githubusercontent.com/8294252/26881257-eecdd61a-4b64-11e7-924a-0418cc42255a.png)
- ...lib64/pkgconfig does not exist

**Comment by mgautierfr** [comment]
Do you have `pgk-config` installed ?
Can you run `PKG_CONFIG_PATH=:/Users/chrisli/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig pkg-config --print-errors icu-18n` in a terminal ?

**Comment by automactic** [comment]
I don't have `pgk-config` installed, so I installed it and run the command above, I got:
```
Chriss-MacBook-Pro:~ chrisli$ PKG_CONFIG_PATH=:/Users/chrisli/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig pkg-config --print-errors icu-18n
Package icu-18n was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-18n.pc'
to the PKG_CONFIG_PATH environment variable
No package 'icu-18n' found
```
And just to be clear `pgk-config` is not required to build `kiwix-build`, it's just for debugging, correct?

**Comment by kelson42** [comment]
The fact tha pkg-config was not installed and this problem was not clearly reported speaks out for this ticket https://github.com/kiwix/kiwix-build/issues/49.

**Comment by mgautierfr** [comment]
@automactic yes, pkg-config is necessary to build kiwix-lib.

@kelson42 There are two things here :
- the fact that `pkg-config` is not declared as a dependencies for `kiwix-lib` (but it is for `meson` and probably `autotools`) . I will add it to `kiwix-build`
- the fact that `kiwix-build` doesn't support macOS. Especially, it doesn't know which packages to install and how to install them.

**Comment by automactic** [comment]
@kelson42, @mgautierfr, how should I proceed? Should I add `pkg-config` to `PACKAGE_NAME_MAPPERS`? Or should I wait till `kiwix-lib` is updated?

**Comment by mgautierfr** [comment]
@automactic No need to add `pkg-config`, the commit https://github.com/kiwix/kiwix-build/commit/844eb9c2ef8ebfedb30dfe9ecd4a7411adf173a5 do it already.

What is missing here, is that I don't know the generic command to install a package (pkg-config and other) on macos. What is mainly missing is the `elif self.distname == 'Darwin'` to complete those lines https://github.com/kiwix/kiwix-build/blob/master/kiwix-build.py#L473:L478 If you know them, I will glady accept your merge request :)

Comming back to our problem, what is the content of `/Users/chrisli/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig` ?(`ls /Users/chrisli/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig`) If there is a `icu-18n.pc` in it, what is its content ?

**Comment by automactic** [comment]
macOS does not come with a package manager, people use stuff like Homebrew or MacPorts.

Here's the file: [icu-i18n.pc.zip](https://github.com/kiwix/kiwix-build/files/1075556/icu-i18n.pc.zip)

**Comment by automactic** [comment]
this issue has been fixed in https://github.com/kiwix/kiwix-lib/pull/58

**Comment by mgautierfr** [comment]
> Also, I have already added ways to check if a package is installed on macOS in apple-platforms branch. https://github.com/kiwix/kiwix-build/blob/apple_platforms/kiwix-build.py#L482:L484

That's nice.

> Here's the file: icu-i18n.pc.zip

That's strange. The file exist and seems good but pkg-config cannot "detect" the lib.
Can you run  : `PKG_CONFIG_PATH=:/Users/chrisli/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig pkg-config --print-errors --debug icu-18n` ?


As a side note :
You merge regularly `master` into your `apple-platforms` branch. I think it is not a good idea. A rebase in this case is far better. If you look at the history of `apple-platforms` (`gitk origin/apple-platforms`) it is very complicated, there is a lot of merge of `master` into `apple-platforms` and all the history is "polluted" by commits coming from `master`. You have something like 10 commits really useful in this branch and they should be easily identifiable. By rebasing `apple-platforms` on `master`, you're keeping your commits on top of `master` and it make the history far more easier to read.
Because of that, independently of the code you have written, I would not merge your branch as it is.
If you don't know how to rebase you branch and clean your history I can do it for you if you want.
And before you ask, I consider that only `master` should be "stable" (no rewrite of history). Other branches are especially here to discuss and tweak the code (and so history) before they go into master and cannot be changed.

**Comment by automactic** [comment]
Output from running above command
```
Chriss-MacBook-Pro:kiwix-build chrisli$ PKG_CONFIG_PATH=:/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig pkg-config --print-errors --debug icu-18n
no output option set, defaulting to --exists
Error printing disabled by default due to use of output options --exists, --atleast/exact/max-version, --list-all or no output option at all. Value of --print-errors: 1
Error printing enabled
Adding virtual 'pkg-config' package to list of known packages
Cannot open directory #1 '' in package search path: No such file or directory
Scanning directory #2 '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig'
File 'blkid.pc' appears to be a .pc file
Will find package 'blkid' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/blkid.pc'
File 'com_err.pc' appears to be a .pc file
Will find package 'com_err' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/com_err.pc'
File 'icu-i18n.pc' appears to be a .pc file
Will find package 'icu-i18n' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/icu-i18n.pc'
File 'icu-io.pc' appears to be a .pc file
Will find package 'icu-io' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/icu-io.pc'
File 'icu-uc.pc' appears to be a .pc file
Will find package 'icu-uc' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/icu-uc.pc'
File 'kiwix.pc' appears to be a .pc file
Will find package 'kiwix' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/kiwix.pc'
File 'liblzma.pc' appears to be a .pc file
Will find package 'liblzma' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/liblzma.pc'
File 'libmicrohttpd.pc' appears to be a .pc file
Will find package 'libmicrohttpd' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/libmicrohttpd.pc'
File 'libzim.pc' appears to be a .pc file
Will find package 'libzim' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/libzim.pc'
File 'pugixml.pc' appears to be a .pc file
Will find package 'pugixml' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/pugixml.pc'
File 'ss.pc' appears to be a .pc file
Will find package 'ss' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/ss.pc'
File 'uuid.pc' appears to be a .pc file
Will find package 'uuid' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/uuid.pc'
File 'xapian-core.pc' appears to be a .pc file
Will find package 'xapian-core' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/xapian-core.pc'
File 'zlib.pc' appears to be a .pc file
Will find package 'zlib' in file '/Volumes/Data/Developer/kiwix-build/BUILD_native_dyn/INSTALL/lib/pkgconfig/zlib.pc'
Scanning directory #3 '/usr/local/lib/pkgconfig'
File 'icu-i18n.pc' appears to be a .pc file
File 'icu-i18n.pc' ignored, we already know about package 'icu-i18n'
File 'icu-io.pc' appears to be a .pc file
File 'icu-io.pc' ignored, we already know about package 'icu-io'
File 'icu-uc.pc' appears to be a .pc file
File 'icu-uc.pc' ignored, we already know about package 'icu-uc'
File 'libcdt.pc' appears to be a .pc file
Will find package 'libcdt' in file '/usr/local/lib/pkgconfig/libcdt.pc'
File 'libcgraph.pc' appears to be a .pc file
Will find package 'libcgraph' in file '/usr/local/lib/pkgconfig/libcgraph.pc'
File 'libgvc.pc' appears to be a .pc file
Will find package 'libgvc' in file '/usr/local/lib/pkgconfig/libgvc.pc'
File 'libgvpr.pc' appears to be a .pc file
Will find package 'libgvpr' in file '/usr/local/lib/pkgconfig/libgvpr.pc'
File 'libpathplan.pc' appears to be a .pc file
Will find package 'libpathplan' in file '/usr/local/lib/pkgconfig/libpathplan.pc'
File 'libpng.pc' appears to be a .pc file
Will find package 'libpng' in file '/usr/local/lib/pkgconfig/libpng.pc'
File 'libpng16.pc' appears to be a .pc file
Will find package 'libpng16' in file '/usr/local/lib/pkgconfig/libpng16.pc'
File 'libtiff-4.pc' appears to be a .pc file
Will find package 'libtiff-4' in file '/usr/local/lib/pkgconfig/libtiff-4.pc'
File 'libxdot.pc' appears to be a .pc file
Will find package 'libxdot' in file '/usr/local/lib/pkgconfig/libxdot.pc'
Cannot open directory #4 '/usr/local/share/pkgconfig' in package search path: No such file or directory
Scanning directory #5 '/usr/lib/pkgconfig'
File 'apr-1.pc' appears to be a .pc file
Will find package 'apr-1' in file '/usr/lib/pkgconfig/apr-1.pc'
File 'apr-util-1.pc' appears to be a .pc file
Will find package 'apr-util-1' in file '/usr/lib/pkgconfig/apr-util-1.pc'
File 'libcrypto.pc' appears to be a .pc file
Will find package 'libcrypto' in file '/usr/lib/pkgconfig/libcrypto.pc'
File 'libecpg.pc' appears to be a .pc file
Will find package 'libecpg' in file '/usr/lib/pkgconfig/libecpg.pc'
File 'libecpg_compat.pc' appears to be a .pc file
Will find package 'libecpg_compat' in file '/usr/lib/pkgconfig/libecpg_compat.pc'
File 'libedit.pc' appears to be a .pc file
Will find package 'libedit' in file '/usr/lib/pkgconfig/libedit.pc'
File 'libiodbc.pc' appears to be a .pc file
Will find package 'libiodbc' in file '/usr/lib/pkgconfig/libiodbc.pc'
File 'libpcre.pc' appears to be a .pc file
Will find package 'libpcre' in file '/usr/lib/pkgconfig/libpcre.pc'
File 'libpcreposix.pc' appears to be a .pc file
Will find package 'libpcreposix' in file '/usr/lib/pkgconfig/libpcreposix.pc'
File 'libpgtypes.pc' appears to be a .pc file
Will find package 'libpgtypes' in file '/usr/lib/pkgconfig/libpgtypes.pc'
File 'libpq.pc' appears to be a .pc file
Will find package 'libpq' in file '/usr/lib/pkgconfig/libpq.pc'
File 'libssl.pc' appears to be a .pc file
Will find package 'libssl' in file '/usr/lib/pkgconfig/libssl.pc'
File 'openssl.pc' appears to be a .pc file
Will find package 'openssl' in file '/usr/lib/pkgconfig/openssl.pc'
Scanning directory #6 '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12'
File 'libcurl.pc' appears to be a .pc file
Will find package 'libcurl' in file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12/libcurl.pc'
File 'libexslt.pc' appears to be a .pc file
Will find package 'libexslt' in file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12/libexslt.pc'
File 'libxml-2.0.pc' appears to be a .pc file
Will find package 'libxml-2.0' in file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12/libxml-2.0.pc'
File 'libxslt.pc' appears to be a .pc file
Will find package 'libxslt' in file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12/libxslt.pc'
File 'sqlite3.pc' appears to be a .pc file
Will find package 'sqlite3' in file '/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12/sqlite3.pc'
File 'zlib.pc' appears to be a .pc file
File 'zlib.pc' ignored, we already know about package 'zlib'
Looking for package 'icu-18n'
Looking for package 'icu-18n-uninstalled'
Package icu-18n was not found in the pkg-config search path.
Perhaps you should add the directory containing `icu-18n.pc'
to the PKG_CONFIG_PATH environment variable
No package 'icu-18n' found
```

**Comment by mgautierfr** [comment]
Ho, you're right. Can you run the same command with `icu-i18n` instead of `icu-18n` ?
I've made a typo in this discussion thread, but  looking in the log of https://github.com/kiwix/kiwix-build/issues/29#issuecomment-306620499, meson correctly tries to search for `icu-i18n`.

**Comment by automactic** [comment]
@mgautierfr kiwix-lib now builds successfully. I don't think we need to continue investigating this any more

**Comment by mgautierfr** [comment]
Great !!
You were probably missing `pkgconfig` and then we investigate with `icu-18n` instead of `icu-i18n`.

I'm closing this issue.

If further compilations fail (kiwix-tools ?), do not hesitate to open a new issue (this one is pretty long already)

If there is few commits in you `apple-platforms` branch that can be merged already in `master`, do not hesitate to create a PR for them. Few small PR are better than a big one.
