### ISSUE TITLE
Update build system on travis

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#311]
We are using the `trusty` release of ubuntu on travis-ci to build (almost) everything.
However :
- Trusty end-of-life is end of april 2019 (ie, this month)
- It appears we have some issue while cross-compiling to windows on old mingw.
- A recent meson is needed (and it needs a python3.5 at least, available by default in xenial)

We should investigate to move to ubuntu `xenial` from `trusty` in Travis-ci.

As a side update, now that travis provides windows machine to build, we could see to build everything using travis instead of using appveyor. (To investigate pros and cons)

**Comment by kelson42** [comment]
@mgautierfr I thought you have upgraded the system by moving on to Docker. Can you confirm an close the ticket if possible?

**Comment by mgautierfr** [comment]
Yes, I confirm.
