### ISSUE TITLE
Documentation about how to update Android dependences

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#336]
It is really not clear what/how to update Android deps in kiwix-build. A small explanation as a wiki page is necessary.

I see at least three things:
* NDK
* SDK
* All other dependences (usually handled directly within google studio)

**Comment by kelson42** [comment]
@mgautierfr @macgills Considering that the would kiwix-android build will be removed from kiwix-build. I think this ticket is not valid anymore. Please confirm.

**Comment by macgills** [comment]
I would say it is no longer valid. I would await confirmation from @mgautierfr

**Comment by mgautierfr** [comment]
> Considering that the would kiwix-android build will be removed from kiwix-build. I think this ticket is not valid anymore. Please confirm.

I didn't understand that we will remove kiwix-android build from kiwix-build.
As far as I have understood, we will add publication of android kiwix-lib's wrapper using a subproject in kiwix-lib (using gradle).

Anyway, the documentation is here (https://github.com/kiwix/kiwix-build/wiki/Change-dependencies-version.) :)

**Comment by macgills** [comment]
The current status of automated publishing in kiwix-android means that we no longer have a dependency on kiwix-build to provide us dependencies at build time.
There are still some questions around custom apps but tickets have been created to own that within kiwix-android

**Comment by kelson42** [comment]
@macgills @mgautierfr Please clarify (again) the stuff about Kiwix-Android compilation/publication between us.
@mgautierfr Thank you for the documentation. What about the packages in `android_sdk.py`, this is also a kind of dependence. Is that a special case?

**Comment by macgills** [comment]
Kiwix-Android now happily compiles release variants for all architectures on CI when a tag is pushed and publishes to alpha of the play store as well as creating a draft release on GitHub releases. I have tickets to migrate nightly publishing and will update GitHub releases to only upload the universal apk.
I also have tickets to make custom apps work much a similar way, I will know more once I start work on those.

**Comment by mgautierfr** [comment]
> Kiwix-Android now happily compiles release variants for all architectures on CI when a tag is pushed and publishes to alpha of the play store as well as creating a draft release on GitHub releases

Yes, but it doesn't mean that kiwix-build will stop to build kiwix-android. This is, at least, useful to have warning when I change (rarely) kiwix-lib jni and be sure that kiwix-android still compile.

And even if kiwix-build doesn't build kiwix-android, it will still build kiwix-lib for android, so it will need the ndk dependency (version, download url).

> What about the packages in android_sdk.py, this is also a kind of dependence. Is that a special case?

No, android_sdk is a dependency of the android platform (not kiwix-android or kiwix-lib) but it is a dependency. It is handle the same way that other dependencies and so, should be updated the same way.

**Comment by macgills** [comment]
> This is, at least, useful to have warning when I change (rarely) kiwix-lib jni and be sure that kiwix-android still compile.

This could be solved by nightly (or on demand) publishing of kiwix-lib SNAPSHOTs and having kiwix-android use the snapshot versions in it's own nightly/local builds.

>it will still build kiwix-lib for android, 

100% agree

**Comment by kelson42** [comment]
@macgills We need to sort-out this "snapshot thing" IMO. This is important, maybe this is only a documentation effort.

**Comment by macgills** [comment]
@kelson42 it is not [just documentation](https://www.quora.com/What-is-the-difference-between-a-snapshot-and-the-release-version-in-the-pom-xml) as I will need to make the uploading task

**Comment by macgills** [comment]
I will follow the guidelines in [this article](https://reflectoring.io/publish-snapshots-with-gradle/) I think, I have requested snapshot hosting for kiwixlib from bintray

**Comment by kelson42** [comment]
@macgills @mgautierfr I this ticket still actual? Do we still have kiwix-build having to download SDK, NDK and other Java/Kotlin libraries?

**Comment by macgills** [comment]
Until custom apps are resolved kiwix-build will have to keep building kiwix-android

**Comment by kelson42** [comment]
@macgills We have finally removed the Android stuff from this repo... but I'm not sure about the needed deps for libkiwix JNI build process. Do we still need documentation here?

**Comment by macgills** [comment]
I don't think so but I know nothing of how kiwix-lib gets built, as matthieu said earlier kiwix-lib needs the NDK, I am unaware of any other dependencies.

**Comment by kelson42** [comment]
@macgills It looks like the only dependence are quite clear now and limited:
* https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/android_ndk.py
* https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/android_sdk.py
