### ISSUE TITLE
Make CI temporary dependencies available through HTTP

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#34]
These dependencies are necessary to compile many repositories without having each time to recompile everything and even more important without having to use kiwix-build.

This dependencies needs to be also available to everybody, otherwise the CI won't be able to test merge requests hosted on external git repositories.

**Comment by kelson42** [comment]
@mgautierfr I have created /var/www/tmp.kiwix.org/ci for the CI user and this is available through http at this address http://tmp.kiwix.org/ci/.

**Comment by mgautierfr** [comment]
This is fixed by cab89b38 and other projects now use the published archives.
We can close this issue.
