### ISSUE TITLE
Remove kiwix-android support.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#344]
With the last change on the kiwix-android side (#343, kiwix/kiwix-lib#231) we will end to a situation where :
- kiwix-android will depend of nothing (it automatically download the kiwix-lib app from jfrog)
- kiwix-android will not be built nor published by kiwix-build ci.

The code of kiwix-build will mainly resume itself to install the sdk and run a single gradle command with the right options.

I think we can simply remove the android support from kiwix-build.
(I am not speaking about removing the compilation of kiwix-lib for android. This is just the kiwix-android apk).

@kelson42 What do you think about this ?

**Comment by kelson42** [comment]
@mgautierfr Good to me!

**Comment by mgautierfr** [comment]
> This is important to make that straight away.

Really ? I'm speaking about removing code we will not use in the CI.
Not about not using it in the CI (this is already done in #343)

**Comment by kelson42** [comment]
@mgautierfr Can we close this ticket? Is that fixed by https://github.com/kiwix/kiwix-build/pull/338 ?

**Comment by kelson42** [comment]
Looks like the README.md still need to be adapted. A few words to redirect people to kiwix-android repo would be welcome.

**Comment by mgautierfr** [comment]
> @mgautierfr Can we close this ticket? Is that fixed by #338 ?

No.
For now, we are not building kiwix-android apk with kiwix-build on the CI. This part has been move to the kiwix-android repository's CI.

This issue is about removing the code in kiwix-build to compile kiwix-android apk.
The README is correct for now because we haven't done anything on the code side.

**Comment by mgautierfr** [comment]
Removing kiwix-android support also means remove the support for building android custom apps.
So code to build it should be move somewhere else (kiwix-android repository ?) and launch from there.

**Comment by kelson42** [comment]
@macgills Could we have a strategy for the custom app? So we know how to go further with this ticket?

**Comment by macgills** [comment]
I have been thinking about custom apps a lot and how I want to proceed is like this:
For each custom app we create a build flavor for kiwix, each custom app will have a directory in the project for it's necessary files (depending on the size of the zims this may need git LFS) and this will enable us to send out updates for all custom apps when we do a release of kiwix-android ,if this is desirable, a limitation of the play store is that you can only upload 15 apps per day.
This is my plan with my current understanding of how the custom apps work.
The other option is to go multi module and convert kiwix-android into a library project.

**Comment by mgautierfr** [comment]
git LFS is appealing but there are some important cons :
- git LFS need a special server. And we don't have it. We could use the one of github but it would means that we duplicate our content in ours server and github. Or we could install a server on our side, but it probably means that we need to keep all versionned zim files (and we currently don't keep old versions)
- We will use git-lfs to download the zim file. We will not be able to use more advanced tools (as aria2, bittorrent, ..) to download zim files.

We could use the same principe that git-lfs (ie store a reference to the zim instead of the zim itself) but it is globally what we are doing in kiwix/kiwix-android-custom.

> This is my plan with my current understanding of how the custom apps work.

There are different steps:
- Build the apk itself. Here nothing really complex on kiwix-build side (https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/kiwix_custom_app.py) most of the work is the same as for classic kiwix-android app, plus the generation of the custom dir (using the script https://github.com/kiwix/kiwix-android-custom/blob/master/gen-custom-android-directory.py in kiwix-android-custom) and launching gradle with the right options.
- Build everything (lib, apk, zim) and publishing it. The easy way is done by the script https://github.com/kiwix/kiwix-build/blob/master/build_custom_app.pl will it could be a bit simplified using last feature of kiwix-build to build for several arch in the raw, all the steps are clearly identifiable.
- Be able to build everything on the CI without compiling locally. (It is mainly intended for non developper manager (@Popolechien) to do new custom app without a full dev environment). The idea is to launch all the build steps on the CI, publish the intermediate artifacts on a server and do the last upload to google locally (and so without revealing secret keys to sign and so). This is handled by https://github.com/kiwix/kiwix-build/blob/master/build_custom_app.py.

As you can see, `build_custom_app.py` is pretty old (2 years) and at the time, we've got some issues with travis where some custom build request were not correctly launched. I don't really know what the exact status on this.

**Comment by macgills** [comment]
In the event we can not store the zim files on git:
```
def f = file(buildscript.sourceFile.parent + "/wikipedia_fr_test_2017-07.zim");
  if (!f.exists()) {
    URLConnection urlConnection = new URL('http://download.kiwix.org/zim/wikipedia_fr_test.zim').
        openConnection()
    urlConnection.connect()
    urlConnection.getInputStream()
    String url = urlConnection.getURL().toString()
    if (urlConnection.getHeaderField("Location") != null) {
      url = urlConnection.getHeaderField("Location")
      url = url.replace("https", "http")
    }
    new URL(url).withInputStream { i -> f.withOutputStream { it << i } }
```
`customExample` build flavour in the android project downloads the zim it wants at build time already.


Building the apk is the simple part, that is defined already for the main app. We just need to create the icon set for each custom app which seems to be only one icon.

What do you mean by "build the zim"? Is there a process that generates a new zim file?

Building on the CI to automatically release is the goal for all of these, on a tag of master we would preform an automated release of every variant of the app to alpha, as is the current behaviour of the main app. I assume the keystore is the same as the main app and there is not a unique one per custom app. We will also easily be able to test locally.

Expansion files are a concern to me, are the majority of the custom apps providing expansion files? It seems like that may not be supported by my gradle plugin and will have to be a manual step to add them to a listing.

**Comment by mgautierfr** [comment]
> What do you mean by "build the zim"? Is there a process that generates a new zim file?

No. No generation of new zim. Please understand "download the zim".

> Expansion files are a concern to me, are the majority of the custom apps providing expansion files? It seems like that may not be supported by my gradle plugin and will have to be a manual step to add them to a listing.

That's the "complex" part. We have to upload the zim file to google as an expansion files.
There is nothing complicated here, just associate the correct version code of the expansion file with the apks, we already do it here https://github.com/kiwix/kiwix-build/blob/master/build_custom_app.py#L394-L408 
But we need to have the zim file locally present from where we do the request. And with 18Go of disk space on travis, we cannot download the zim file just to upload to google. This is why the dl of zim file and upload of all apk is made locally and not on travis.

**Comment by macgills** [comment]
This line confused me
> Build everything (lib, apk, zim)

so I thought it best to clarify.

We currently upload the apks to alpha in draft so it should be possible to update that draft with expansion files I think.

Are the majority of apks using expansion files or are the majority just bundled with the apk?
Do we only use primary expansion files or do we sometimes use secondary?
How often do we release/update custom apps? 

Releasing a new app may cause a problem for the first upload
> registering the app with the Play Store cannot be done using the Play Developer API

**Comment by mgautierfr** [comment]
> This line confused me

Well, it was just a little sentence to say "do all the things together"

> We currently upload the apks to alpha in draft so it should be possible to update that draft with expansion files I think.

Yes totally.

> Are the majority of apks using expansion files or are the majority just bundled with the apk?
Do we only use primary expansion files or do we sometimes use secondary?
How often do we release/update custom apps?

I'm not the expert of the android side of kiwix (@kelson42 or @mhutti1 are better placed to answer) but :
- It depends of the size of the zim file. If the zim file is small enough we bundled it. Else we use expansion file. But I don't know the limit size.
- Mainly primary expansion files I think
- Not as often as we would like :)

> Releasing a new app may cause a problem for the first upload

Yes, I've forget about this. The creation of a new custom app has to be done manually from the google console web page. (I'm not sure if the first upload can be done through the API).

**Comment by mhutti1** [comment]
My question is how can one test kiwix-lib changes without needing to upload to bintray?

**Comment by kelson42** [comment]
@mhutti1 Really important question to me too. This is the purpose of #345.

**Comment by mhutti1** [comment]
This still won't help with debugging though? I could probably get something right in 1-2 attempts but its really easy to mess up your headers and end up with something that doesn't work.

**Comment by macgills** [comment]
Then I would propose a test project in kiwixlib if only to run automated tests or something similar. A full integration with kiwix-android should not be necessary to make sure additions to a separate project work.
If this gets integrated with ci then we can independently validate on each PR. I am assuming unit tests are all but impossible

**Comment by mgautierfr** [comment]
#345 is about publishing snapshot somewhere. This will not answer the question of "how can one test kiwix-lib changes without needing to upload to bintray ?".
There is a more interesting discussion on #346. The issue is not about this but we hijack the thread to speak about how to test the kiwix-lib in android application.

**Comment by kelson42** [comment]
@mgautierfr @mhutti1 @macgills I would recommend to discuss how to allow testing of libkiwix <-> kiwix-android within #346
