### ISSUE TITLE
Add SNAPSHOT publishing of kiwix-lib on Nightly builds

### ISSUE THREAD

**Issue by macgills** [kiwix/kiwix-build#345]
To enable the rapid testing of the latest code in kiwix-lib we want to publish to artifactory nightly.

I was following [this article](https://reflectoring.io/publish-snapshots-with-gradle/) on how to do it for gradle.

The end result is that the android project can switch from
`implementation 'org.kiwix.kiwixlib:kiwixlib:<CURRENT_VERSION>'`
to
`implementation 'org.kiwix.kiwixlib:kiwixlib:<NEXT_VERSION>-SNAPSHOT'`
at will

**Comment by kelson42** [comment]
I think we should do so and publish automatically via CA our git master HEAD to bintray to a `dev` snapshot. I would keep only one name/tag for that version an don't keep any history of it. This would not e a solution to the #346 problem, but would allow people to use cutting-edge version of the libkiwix withough having to compile it.

**Comment by kelson42** [comment]
@mgautierfr Should such a dev version based on master be uploaded to bintray by kiwix-build or directly from kiwixlib repo?

**Comment by kelson42** [comment]
@mgautierfr AFAIK, we publish both libzim anf libkiwix binaries meanwhile in nightlies. Same will happen with java-libkiwix once its over.
