### ISSUE TITLE
Kiwix librairies for Android are more than twice as big than before

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#348]
This does not sound to be normal to me... and our APKs are huge as a consequence :(

![image](https://user-images.githubusercontent.com/1029718/61140032-f3137b00-a4ca-11e9-8b67-387921d975ea.png)
![image (1)](https://user-images.githubusercontent.com/1029718/61140029-f27ae480-a4ca-11e9-8ee6-b9d3fe05cc84.png)

**Comment by mgautierfr** [comment]
This is probably because the apk contains libraries I've made on my system and I give to @macgills to test everything works. This is debug build and they are not stripped or size optimized.

This is just a assumption but I'm pretty confident this is it because the build system to publish the kiwix-lib for android is not merged yet.

We should check the size again once we will have a release made by kiwix-build.

**Comment by kelson42** [comment]
@mgautierfr I don't think so, nightly builds have the problem https://download.kiwix.org/nightly/2019-07-19/

**Comment by mgautierfr** [comment]
Nightly builds are debug builds.

**Comment by kelson42** [comment]
@mgautierfr Does including debug symbols explains why the lib twice as big?

**Comment by mgautierfr** [comment]
Yes, you can compare https://download.kiwix.org/nightly/2019-07-19/kiwix-tools_linux-x86_64-2019-07-19.tar.gz (debug) and https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-x86_64-2.0.0.tar.gz (release) for example.

**Comment by mgautierfr** [comment]
As I said, this is an assumption. We may have a real issue, or not. But for now this is useless to investigate further if we only have debug build. We need to have release build to compare things correctly.

**Comment by kelson42** [comment]
@mgautierfr Looking at APK releases, we have a jump by factor two between 2.4 and 3.0 https://download.kiwix.org/release/kiwix-android/.

**Comment by macgills** [comment]
Our apps are below 14MB on the play store, they could probably be smaller but this is still quite slim

**Comment by kelson42** [comment]
Things seems back under control.
