### ISSUE TITLE
Appveyor doesn't report status to github anymore.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#353]
The builds are correctly triggered but the status is not reported.
As the appveyor CI is required to merge the PR, github blocks the PR. I have to use my "administrator privilege" to bypass this.

We have to investigate this.
We had the same with travis (almost in the same time). We fix this by requesting the access rights for travis app on the kiwix organization.
I've done the same with appveyor but @kelson42 never receive the mail to confirm the request. (And I don't know how to resend it)

**Comment by kelson42** [comment]
@mgautierfr Ijust have found a request from you for Appveyor on the Github Web UI and accepted it. Hopefully this will fix that ticket.

**Comment by mgautierfr** [comment]
It works now. Thank.
