### ISSUE TITLE
Publish libkiwix for iOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#359]
This is necessary for Kiwix iOS CI: https://github.com/kiwix/apple/issues/159

**Comment by kelson42** [comment]
@automactic I think we should move soon on this. Would you be able to specify here what you need exactly to be published? Maybe another solution than Bintray would be more convenient for you?

**Comment by kelson42** [comment]
Bintray does not exist anyway, but ot looks we could just publish it to download.kiwix.org and this would be perfect.

**Comment by mgautierfr** [comment]
Duplicate of #455
