### ISSUE TITLE
Appveyor CI should be able to publish binaries with specific build version

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#363]
But we have a version for all other systems.

@mgautierfr This is not the first time we fail to publish binaries properly and each time this is detected by users. What can we do to avoid this problem and/or detect it properly on time?

**Comment by mgautierfr** [comment]
There is no system on windows CI to publish the build under a different name using a build version.
So `kiwix-desktop_windows_x64_2.0-rc1-1.zip` is not publish but `kiwix-desktop_windows_x64_2.0-rc1.zip` replacing the older one.

**Comment by kelson42** [comment]
@mgautierfr So you need to handle that manually (making a backup and move and reupload files manually)?

**Comment by mgautierfr** [comment]
No, we have to change the appveyor publication script to correctly publish the release under a different name
