### ISSUE TITLE
make command is giving error cannot find -lkiwix and cannot find -lpugixml

### ISSUE THREAD

**Issue by ayusdas2000** [kiwix/kiwix-build#370]
I am using Ubuntu 18.04 64 bit.
I tried building Kiwix-desktop
Used the command qmake . worked well only with some syntax errors in the .js file.
Then on running make command it says cannot find -lkiwix and -lpugixml despite add the path through LD_LIBRARY_PATH="<...>/BUILD_native_dyn/INSTALL/lib/x86_64-linux-gnu" this command

**Comment by kelson42** [comment]
@ayusdas2000 You are not using kiwix-build. You build Kiwix directly from the kiwix-desktop directory. This is the wrong repository. This ticket should be in the kiwix-desktop directory. That said, if you are not familliar with compilation, we strongly recommend to use Kiwix-build.
