### ISSUE TITLE
Compilation Error on ElementaryOS

### ISSUE THREAD

**Issue by SarveshBajaj** [kiwix/kiwix-build#386]
Hi, I'm trying to build on ElementaryOS -- a distro based on Ubuntu 16.04, after installing all dependencies as stated on the README, I'm getting the following log:

(env_kiwix) sarvesh@lucifer:~/Documents/kiwix/kiwix-build$ kiwix-build
ERROR: The target platform native_dyn cannot be build on host elementary.
Select another target platform or change your host system.
[INSTALL PACKAGES]
SKIP, No package to install.
[SETUP PLATFORMS]
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources uuid :
  download uuid : SKIP
  extract uuid : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
  patch xapian-core : SKIP
prepare sources icu4c :
  download icu4c : OK (205.0s)     
  extract icu4c : OK (4.0s)
  patch icu4c : OK (0.0s)
prepare sources libzim :
  gitclone libzim : OK (3.2s)
  gitupdate libzim : OK (1.2s)
prepare sources libcurl :
  download libcurl : OK (8.1s)
  extract libcurl : OK (0.8s)
prepare sources libmicrohttpd :
  download libmicrohttpd : OK (8.8s)
  extract libmicrohttpd : OK (0.2s)
prepare sources mustache :
  download mustache : OK (1.3s)
  extract mustache : OK (0.0s)
  patch mustache : OK (0.4s)
prepare sources kiwix-lib :
  gitclone kiwix-lib : OK (8.7s)
  gitupdate kiwix-lib : OK (1.1s)
prepare sources kiwix-tools :
  gitclone kiwix-tools : OK (3.4s)
  gitupdate kiwix-tools : OK (1.2s)
[BUILD]
build pugixml (native_dyn):
  configure pugixml : OK (2.4s)
  compile pugixml : OK (5.4s)
  test pugixml : OK (0.3s)
  install pugixml : OK (0.3s)
build zlib (native_dyn):
  pre_build_script zlib : OK (0.1s)
  configure zlib : OK (1.7s)
  compile zlib : OK (2.7s)
  install zlib : OK (8.9s)
build lzma (native_dyn):
  configure lzma : OK (7.8s)
  compile lzma : OK (5.8s)
  install lzma : OK (0.7s)
build uuid (native_dyn):
  configure uuid : OK (12.3s)
  compile uuid : OK (1.2s)
  install uuid : OK (0.3s)
build xapian-core (native_dyn):
  configure xapian-core : OK (8.2s)
  compile xapian-core : .OK (42.4s)
  install xapian-core : OK (1.1s)
build icu4c (native_dyn):
  configure icu4c : OK (4.1s)
  compile icu4c : ...OK (101.1s)
  install icu4c : OK (0.8s)
build libzim (native_dyn):
  configure libzim : OK (6.4s)
  compile libzim : OK (17.7s)
  test libzim : OK (4.4s)
  install libzim : OK (3.7s)
build libcurl (native_dyn):
  configure libcurl : OK (23.8s)
  compile libcurl : OK (10.7s)
  install libcurl : OK (2.2s)
build libmicrohttpd (native_dyn):
  configure libmicrohttpd : OK (9.4s)
  compile libmicrohttpd : OK (2.2s)
  install libmicrohttpd : OK (0.3s)
build mustache (native_dyn):
  copy_header mustache : OK (0.0s)
build kiwix-lib (native_dyn):
  configure kiwix-lib : OK (4.6s)
  compile kiwix-lib : OK (22.2s)
  test kiwix-lib : OK (4.7s)
  install kiwix-lib : OK (4.7s)
build kiwix-tools (native_dyn):
  configure kiwix-tools : OK (0.7s)
  compile kiwix-tools : OK (1.2s)
  test kiwix-tools : OK (0.3s)
  install kiwix-tools : OK (0.4s)
[CLEAN]
SKIP

How should I proceed further?

**Comment by kelson42** [comment]
@SarveshBajaj Which software exactly do you want to build? Kiwix build allow to build many Kiwix softwares.

**Comment by kelson42** [comment]
@SarveshBajaj No feedback. I close the ticket, please answer and I will reopen it.
