### ISSUE TITLE
Use Qt 5.13

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#403]
We have few issue with "old" version of Qt. Qt 5.13 seems to fix them.

- https://github.com/kiwix/kiwix-desktop/pull/346#issuecomment-579167803
- https://github.com/flathub/org.kiwix.desktop/pull/4
- https://github.com/kiwix/kiwix-desktop/issues/176
- https://github.com/kiwix/kiwix-desktop/issues/255
- https://github.com/kiwix/kiwix-desktop/issues/433
- https://github.com/kiwix/kiwix-desktop/issues/430

However, we use Qt in a lot of place and we need to update it everywhere :
- AppImage: We use the Qt installed by the system (5.9). It seems that we can use snap to install a 5.13 version (https://snapcraft.io/install/webengine513/ubuntu)
- Flatpak: The kde sdk (5.13) doesn't containt qwebengine anymore (https://bugs.kde.org/show_bug.cgi?id=414175). We need to update the generation of our manifest to use the base app https://github.com/flathub/io.qt.qtwebengine.BaseApp . For now, we use 5.12
- Windows: We use the Qt(s) installed by appveyor. There is several versions installed (including 5.13). We just have to use it (we currently use 5.12).

**Comment by kelson42** [comment]
@mgautierfr We should probably move to Qt 5.15 now!

**Comment by mgautierfr** [comment]
Related to https://github.com/flathub/org.kiwix.desktop/pull/6
