### ISSUE TITLE
Incorrectly built physics.stackexchange.com_en_all.zim

### ISSUE THREAD

**Issue by tigran123** [kiwix/kiwix-build#410]
I would like to report a serious bug in the zim file of physics.strackexchange (the 3GB file download from http://download.kiwix.org/zim/physics.stackexchange.com_en_all.zim with MD5 checksum 5d40859320f27ad9839ffe0ce845be3d ). The problem is that during the creation of the zim file MathJax was not enabled and so the LaTeX input is displayed in the raw, i.e. humanly unreadable form (tested both in the Chrome browser and on Android using Kiwix Application). That makes the whole archive useless, because physics is all about formulae and not ASCII text. Please note that the 7.3GB math.stackexchange zim file (MD5 602883446fbe5d8b8b4c9e70dc79718c) has NO problem, i.e. it was compiled correctly and MathJax renders the formulae absolutely fine. Thank you.

I realise that this github repository is not absolutely the best place to report this problem, but I could not find any other place, i.e. all other repositories were even more unrelated --- at least the build tools are what was used to compile the zim file and there is a slight chance that there is an error here which caused MathJax to be enabled at one point (when creating math.stackexchange) and not at some other point.

**Comment by kelson42** [comment]
@tigran123 Thank you for your ticket, I will move the ticket.
