### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution

### ISSUE THREAD

**Issue by shubhamcodez** [kiwix/kiwix-build#415]
I was building Kiwix from source .
I encountered the following error .

AttributeError: module 'platform' has no attribute 'linux_distribution'

 I researched about it ,its because Python 3.8.2 has removed the above mentioned attribute .
I guess it's a compatiblity error and can be resolved from the Kiwix's side.

I'm sorry if I'm wrong.

**Comment by mgautierfr** [comment]
You are right. The feature is deprecated, we must use https://pypi.org/project/distro instead.

**Comment by shubhamcodez** [comment]
Hey I'm having another issue.

I can't build Kiwix using Python 3.7 either

It's giving me Timeout while testing the Build.

Warm Regards

Shubham Singh

**Comment by mgautierfr** [comment]
Please open a new issue for a another issue :) (I've already done it here #421)
