### ISSUE TITLE
Publish libkiwix for macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#418]
To be able to build Kiwix for macOS easily, the libkiwix needs ot be available easily and publicly in a precompiled form.

**Comment by kelson42** [comment]
@automactic I think we should move soon on this. Would you be able to specify here what you need exactly to be published? Where should be this package published (on download.kiwix.org? Bintray?)

**Comment by mgautierfr** [comment]
I would like to mention the initial plan was to publish only static binaries (executable).
Libraries are pretty difficult to distribute precompiled. All dependencies has to be included in the library.
It lead to potential code duplication (for example dependencies as icu or xapian may be included in kiwix-lib (as static lib) and also being use by final application (as dyn lib)) and potential version conflict.

It as been done for android's kiwix-lib and nodejs libzim wrapper because we don't have the choice but I would really like to avoid this.

**Comment by kelson42** [comment]
@mgautierfr What is the alternative then?

**Comment by mgautierfr** [comment]
Why not using kiwix-build ?

**Comment by kelson42** [comment]
@mgautierfr This is a feature request for kiwix-build, so "yes" we talk about kiwix-build. What you mean probably is that developer should use kiwix-build to compile everything themselves.

To me kiwix-build is good to run on GNU/Linux and is already complex. MacOS/iOS developers have their own tools to develops apps and this would be a burden for them to use an exotic way to compile their app.

In a way this is quite similar to the Android case. Remember, not so far ago we were compiling Kiwix-Android with kiwix-build and everybody was working with GNU/Linux to get everything compiled (for the others we had binaries in the git). This was so much worse than today.

Regarding your concern about code duplicates. This is a problem, but not a unsolvable one, and in the worse case we use a bit too much memory, which is an acceptable price to pay here.

**Comment by mgautierfr** [comment]
> Regarding your concern about code duplicates. This is a problem, but not a unsolvable one, and in the worse case we use a bit too much memory, which is an acceptable price to pay here.

I'm not concern about the memory size but about the conflict in version. What happends if we include xapian version X in kiwix-lib and the project also use xapian Y. What would be the version actually used by the project ? Will it depends of the order of the include directories ? Of the order in which libraries are loaded ? We may have the project compiling with version Y headers and linking with version X.

And yes, this is the same with android. But on android side, the app is in java. The only jni used is for kiwixlib.so, nothing else (at least for now). And we have problem on android already. We embed icu in kiwixlib and we need to load the icu data at runtime before using it. But the data is in the kiwix-android side and not in the kiwix-lib.aar. If we change the icu version we also need to change the data. And I don't speak about the fact that there is propably an icu implementation in android already.
On android we toke care about compiling libkiwix using the oldest sdk possible to be compatible with the most devices possible, assuming that android doesn't break compatibility between version.

I don't know how it is on macos/ios side. But we have to answer all those questions before simply drop a libkiwix.so on a server.
It may be easy or not. I just don't know. But we cannot copy the .so on a server and assume we are good.

---
Yes, software distribution is a nightmare. This is why we have so much (concurrent) packaging systems. (rmp, deb, howebrew, appimage, chocolatey, pip, npm, ...)
This is why there is the "war" package everything individually and be sure everything is coherent (linux packaging system) VS bundle everything and run everywhere (appimage,..). Distributing a dynamic library embedding static ones is just being in the middle and we will have problems.

**Comment by automactic** [comment]
For me, I am happy if I can get all the .h files and .a files zipped up in a zip file hosted somewhere. 

Also the propose here is less about distribute libkiwix as a package through homebrew or something. I think it is more about build the app without having to go through the trouble of building everything from scratch. For example, it would be very inefficient if every test on CI have to spend a lot of time building the dependencies.

**Comment by kelson42** [comment]
> And yes, this is the same with android. But on android side, the app is in java. The only jni used is for kiwixlib.so, nothing else (at least for now).

This should not be different on macOS, but we make it available for Swift.

> And we have problem on android already. We embed icu in kiwixlib and we need to load the icu data at runtime before using it. But the data is in the kiwix-android side and not in the kiwix-lib.aar. If we change the icu version we also need to change the data. And I don't speak about the fact that there is propably an icu implementation in android already.

I have already answered about the memory consumption and for the rest related to libicu this is a fixable detail https://github.com/kiwix/kiwix-android/issues/9.

> On android we toke care about compiling libkiwix using the oldest sdk possible to be compatible with the most devices possible, assuming that android doesn't break compatibility between version.

We should take care about that as well... but the problem is a lot simplier for macOS as we don't go so far in the past.

**Comment by kelson42** [comment]
Fixed by @rgaudin with https://github.com/kiwix/kiwix-build/pull/445

**Comment by kelson42** [comment]
@automactic Would you be able to tell us how/where this library should be provided? Would be something like we do for the libzim appropriate? See https://download.openzim.org/release/libzim/

**Comment by kelson42** [comment]
@mgautierfr We have now https://download.kiwix.org/release/libkiwix/libkiwix_macos-x86_64-12.0.0.tar.gz. Does that should implement this ticket?

**Comment by rgaudin** [comment]
@kelson42 this file is buggy: it only contains headers. It should be removed as it is misleading

**Comment by kelson42** [comment]
@mgautierfr I guess you have fixed this with https://github.com/kiwix/kiwix-build/pull/584 ?

**Comment by rgaudin** [comment]
No.
