### ISSUE TITLE
Build kiwix projects for Windows in the CI using github actions instead of appveyor.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#425]
The compilation of kiwix-desktop (and all dependencies) is now made on appveyor.

It is a whole process completely separated of kiwix-build and other CI.

So it is pretty complex to test on each project's CI if the PR compile on windows (on so, we don't).
We end sometime to merge code that compile on unix but not portable on window.

Now that github's action has a windows runner, we should investigate to also compile on windows using github actions.

This may not be a simple task:
- We must ensure that all c++ projects are build with the same compiler for ABI compatibilities (as we use a prebuild version of QT compile with VC++, we must use it everywhere)
- Some python tools (kiwix-build) assume a shell is available to launch subcommands)
- There are some dependencies that are use only on windows (some wrapper to provides pthreads interface). We must add it to kiwix-build (or move our projects to c++ threads library, hoping that no dependencies need pthreads).
- Compilation of windows may be "difficult" for dependencies using autotools on windows. There is mingwing/cygwin that can help here, but remember the first point.
- ...

See https://github.com/kiwix/kiwix-desktop/wiki/kiwix-desktop-windows.

**Comment by mgautierfr** [comment]
Moving the whole kiwix-build tool to windows is blocked by https://github.com/mesonbuild/meson/issues/7838
We may use CMakeFile to build pugixml instead of meson (as last pugixml version provides a CMakeFile), but I'm afraid that we face the same problem with "our" projects (libzim, kiwix-lib, ...)

**Comment by kelson42** [comment]
@mgautierfr This issue needs an update, we have no PR linked!
