### ISSUE TITLE
Documentation on memory and storage requirements missing

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/kiwix-build#426]
When I run `kiwix-build libzim` (I actually wanted to build kiwix-desktop, but stumbled upon this one), test libzim test failed.

It was shown that cluster test failed. It turned out that /tmp was full because of 4Gb folder /tmp/test_cluster_JBOdRV . I deleted this directory (maybe there was data from several failed installations, when I had low bandwidth). When I rerun kiwix-build, it creates a new test_cluster tmp directory and fills it 4 Gb pretty quick. No surprise the test fails after that. I think 4Gb for a test is pretty much, with all due respect to libzim (or it must be written explicitly in requirements).

It's also a pity that the reason of failure is not printed (I discovered that by chance, when tmp was reported full when I ran another command).

I'm using a laptop with Fedora Core 29, if that matters.

P.S. I finally found that this problem exists and is reported (https://github.com/openzim/libzim/issues/147#issuecomment-394307104). I'm very sure that if large memory is a requirement for kiwix, it must be written explicitly on its page (and how to skip that, because users don't necessarily want their programs tested).
I'd make this a documentation bug, but can't categorize it here, and please don't close that until the docs (README) are fixed.

**Comment by ynikitenko** [comment]
export SKIP_BIG_MEMORY_TEST=1

solves the problem, but it should be documented as well.

**Comment by kelson42** [comment]
Yes, kind of duplicate of #398

**Comment by kelson42** [comment]
I have updated the documentation of libzim:
https://github.com/openzim/libzim/commit/2e985094b65ec8e29f3d4859aeff96b523ded197

**Comment by ynikitenko** [comment]
@kelson42  - yes, this was a duplicate, but the original one was closed unfixed. Great that you finally fixed that, thanks!
