### ISSUE TITLE
wrong paths in kiwix-desktop

### ISSUE THREAD

**Issue by ynikitenko** [kiwix/kiwix-build#427]
I'm not sure whether I should open an issue here or on kiwix-desktop. Anyway I compile that with kiwix-build.

When I run `kiwix-build kiwix-desktop`, I receive errors like

    In file included from ../../SOURCE/kiwix-desktop/src/mainwindow.h:6,
                 from ../../SOURCE/kiwix-desktop/src/mainwindow.cpp:2:
    ../../SOURCE/kiwix-desktop/src/webview.h:4:10: fatal error:     QWebEngineView: No such file or directory
     #include <QWebEngineView>
          ^~~~~~~~~~~~~~~~
    compilation terminated.
    make: *** [Makefile:714: mainwindow.o] Error 1

And similar ones. 

On Fedora Core 29 this file is located at `/usr/include/qt5/QtWebEngineWidgets/QWebEngineView`. There are many directories in `/usr/include/qt5/`, and I have to include each of them to INCPATH in `kiwix-build/BUILD_native_dyn/kiwix-desktop/Makefile`.

After that these errors disappear (for another type errors). Please, add includes like

    #include <QtWebEngineWidgets/QWebEngineView>

to kiwix files. Also `-I/usr/include/qt5/` should probably be added to the Makefile (at least on Fedora Core this path seems to be the actual one).

**Comment by mgautierfr** [comment]
Qt include path are detected using qmake. And it depends on the version of qmake you are using.
What is the output of `qmake --version` ?

**Comment by kelson42** [comment]
> Simple `qmake` doesn't work

You mean you have no binary called `qmake` ? You have only one called `qmake-qt5`?

**Comment by mgautierfr** [comment]
You probably need to install `qtchooser` package.

**Comment by ynikitenko** [comment]
I have only qmake-qt4, qmake-qt5 and qmake-qt5.sh. 
I didn't have qmake and qt packages and had to install that. 
This may be strange, but after several days I don't remember well how I installed that. From history I can find that I exported

> export PATH=/usr/lib64/qt5/bin/:$PATH

In that directory there is a command `qmake`, this just isn't present in my usual PATH. `qmake` isn't added to default installation directories. 

Anyway the binary I wrote above is the version used during the build.

**Comment by mgautierfr** [comment]
Can you remove the `BUILD_native_dyn/kiwix-desktop` directory and re-run `kiwix-build kiwix-desktop` ?
And then copy the content of `BUILD_nativy_dyn/LOGS/cmd_configure_kiwix-desktop.log` ?

**Comment by ynikitenko** [comment]
After I removed the directory, skipped the big test and updated PATH to include `qmake` (the first time it just didn't find that), all was compiled well! I don't know why it changed. Do you still need the log?

**Comment by mgautierfr** [comment]
> Do you still need the log?

No. Ideally we should have keep the old log. But we were a bit to hurry :/
Anyway, I'm closing the issue if everything is ok.
