### ISSUE TITLE
Fix issue with libkiwix static compilation on bionic.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#447]
The static compilation of kiwix-lib fails on bionic.

This is due to undefined reference into libidn2. We don't use libidn directly and it seems it is a problem with libcurl.
It is probably related to https://github.com/kiwix/kiwix-build/issues/317

We don't need right now to compile on bionic in static, we are building in xenial by default and we build on bionic only for kiwix-desktop (so dynamically).
But we will need to do it.

Trace of the failing build can be found here : https://github.com/kiwix/kiwix-build/runs/753426498?check_suite_focus=true

**Comment by kelson42** [comment]
@legoktm Do you have a feedback about that? I wanted as well to check the content of `libkiwix9` package but `apt-file show libkiwix9` gives nothing, is that normal?

**Comment by kelson42** [comment]
@mgautierfr Is this bug still occuring?

**Comment by kelson42** [comment]
@mgautierfr Still a bug?

**Comment by mgautierfr** [comment]
Seems not (https://github.com/kiwix/kiwix-build/runs/6380574341?check_suite_focus=true)
