### ISSUE TITLE
Release publication should create a "latest" link.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#448]
Several tools now download the build release on there CI.
When we publish a new version, we need to update the version number in those CIs.

The publication process should create/update a "latest" symlink to the last version to simplify the use of those release.

And it will be useful for all users anyway.

**Comment by kelson42** [comment]
We have a permalink, take a normal link and remove the version number.

**Comment by mgautierfr** [comment]
`wget https://download.openzim.org/release/libzim/libzim_linux-x86_64.tar.gz` doesn't work.

**Comment by mgautierfr** [comment]
And I think that having a "real" symlink make this feature discoverable and it is used in a lot of other projects.

**Comment by kelson42** [comment]
I will this

**Comment by kelson42** [comment]
Done, was as well a duplicate of https://github.com/kiwix/maintenance/issues/128
