### ISSUE TITLE
kiwix-build PR should not overwrite deps archives.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#450]
Discussing with @MiguelRocha, we realize that the base dependencies for other CI are overwritten by the kiwix-build CI all the time.
It is nice as we can regenerate this archive with a PR to test the change in another CI. But in the same time, if the change is wrong, we may break everything.

We should change this to be more tolerant to invalid change. (But we still want to publish the deps archive and be able to use it in another CI as it is the only way to test it).

**Comment by kelson42** [comment]
@mgautierfr Might that be that this has been fixed with #651?

**Comment by mgautierfr** [comment]
Yes, it is fixed.
I had totally forgot about this issue.
