### ISSUE TITLE
Publish libkiwix binaries for iOS/macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#455]
To be able to build Kiwix for macOS easily, the libkiwix needs ot be available easily and publicly in a precompiled form.

**Comment by kelson42** [comment]
@automactic Where should be published this library? Under which form? Woudl be a tarball on download.kiwix.org/release/libkiwix good enough?

**Comment by automactic** [comment]
Like I said in my comment earlier, simply uploading them to a place would be good enough

**Comment by kelson42** [comment]
So just uploading a libkiwix.dynlib?

**Comment by rgaudin** [comment]
@automactic, in the light of signing and notarization requirements and the fact that we'd want to release libkiwix so we can release kiwix-tools for macOS as well, I'd like your opinion on the way to do it.

My (limited) understanding is that the way to go now, is to use an xcframework with all the statically-compiled libkiwix for each archs (arm/x86) and platforms (macOS/iOS).

We'd publish this archive and you'll be able to use it directly in Kiwix for iOS and macOS and others will be able to use it as well.

I understand that Xcode projects would reference it and automatically bundle only the matching arch/plat libs. Other tools might extract the appropriate lib from the xcframework and use it. That might mean notarizing each dylib individually.

Sample of what I imagine the outputs would be:

```
# single-lib, dynamic library. signed+notarized individually
libkiwix.xcframework/
  ios-arm64/
    Headers/
    libkiwix.dylib
  ios-x86_64-simulator/
    Headers/
    libkiwix.dylib
  macos-arm64/
    Headers/
    libkiwix.dylib
  macos-x86_64/
    Headers/
    libkiwix.dylib

# single archive to link statically
libkiwix-static.xcframework/
  ios-arm64/
    Headers/
    libkiwix.a
  ios-x86_64-simulator/
    Headers/
    libkiwix.a
  macos-arm64/
    Headers/
    libkiwix.a
  macos-x86_64/
    Headers/
    libkiwix.a
```

So, would that the desired approach?

**Comment by imustbebored** [comment]
Hello, can someone please do this? I have been trying to build kiwix for iOS and followed the instructions in the readme multiple times, but I am always receiving the following errors
![errors](https://user-images.githubusercontent.com/7050662/147722752-fb04b04d-e0fb-441d-a0e7-8bab41a0ae9f.png)
:

**Comment by kelson42** [comment]
I can not promise anything, but this ticket (and a few others around macOS/iOS/Android) publishing of binaries should be fixed in the next 2 months. Thank you @imustbebored to remember us that it ahould be easy for new devs to step-in.

**Comment by imustbebored** [comment]
> 

Thank you for the reply kelson. You rock.

I managed to get the iOS app running properly in the simulator, but still seem to be having issues regarding testing on actual physical iOS devices. It's strange because when I generated libkiwix.xcframework, I did so for both  iOS_x86_64 and iOS_arm64. Not sure why it would be complaining that it can't find the library when deploying to an actual physical iphone. My understanding was that by targeting both iOS_x86_64 and iOS_arm64 that this should be compatible with both the simulator and physical devices. 

I followed the directions listed here exactly: https://github.com/kiwix/apple

Is this only for the simulator or is there something I'm missing?

**Comment by kelson42** [comment]
@imustbebored Sorry, I can not help you further here as I'm not a Kiwix for iOS dev.
@automactic Would you be able to help @imustbebored please?

**Comment by kelson42** [comment]
@imustbebored We will clearly put the priority now to achieve this within the next weeks.
@automactic Please have a look again to this comment https://github.com/kiwix/kiwix-build/issues/455#issuecomment-777309682. We really need to know for both macOS and iOS what should be published for binaries and which form so it can be directly usable to compile Kiwix 3.0 for macOS & iOS.

**Comment by kelson42** [comment]
We need that very urgently now for Apple custom App project.

Considering that we need to support different architectures, this would make:
* iOS/ARM(64?)
* macOS/ARM64
* macOS/x86
