### ISSUE TITLE
test libzim : ERROR

### ISSUE THREAD

**Issue by vishal-1408** [kiwix/kiwix-build#458]
Hi, II am a first timer to kiwix and i  wanted to build **kiwix-desktop** using **kiwix-build** command. I have encountered an issue in this process,
compiel libzim works fine but the next step : 

 **test libzim : ERROR**

I have even tried using `kiwix-build libzim` ,
even then got the same error :

 **test libzim : ERROR** 

![Screenshot from 2020-07-21 21-53-19](https://user-images.githubusercontent.com/54095062/88080808-2e945b00-cb9d-11ea-8f47-6efaba2a9c41.png)
![Screenshot from 2020-07-21 21-53-54](https://user-images.githubusercontent.com/54095062/88080824-32c07880-cb9d-11ea-92f5-01119b1f3cca.png)
![Screenshot from 2020-07-21 21-55-27](https://user-images.githubusercontent.com/54095062/88080847-4075fe00-cb9d-11ea-95f8-ec6a039e6347.png)
![Screenshot from 2020-07-21 21-56-51](https://user-images.githubusercontent.com/54095062/88080868-479d0c00-cb9d-11ea-92ed-95ea81a69e9c.png)
![Screenshot from 2020-07-21 21-57-04](https://user-images.githubusercontent.com/54095062/88080870-4966cf80-cb9d-11ea-8775-5f3a9432da73.png)

Is there any other way of building the kiwix-desktop without using kiwix build ?

**Comment by veloman-yunkan** [comment]
See #426 

The solution is to set the `SKIP_BIG_MEMORY_TEST` environment variable:

```
export SKIP_BIG_MEMORY_TEST=1
```

**Comment by kelson42** [comment]
I think this should really work the other way around, per default does not make that test. Too many people are stuck there.

**Comment by vishal-1408** [comment]
Thanks a lot @veloman-yunkan , Error is resolved by setting the SKIP_BIG_MEMORY_TEST environment variable.
