### ISSUE TITLE
When is the optimal time to run travis cron jobs?

### ISSUE THREAD

**Issue by mhutti1** [kiwix/kiwix-build#46]
Travis has a concurrent job limit of I think 5 tasks per org. Kiwix build can delay pull request buids by around an hour. Might it be a better idea to schedule these builds at less active times?

**Comment by kelson42** [comment]
No clue about that, I think @mgautierfr should be able to help you for that question.

**Comment by mgautierfr** [comment]
We can schedule recurrent build at only three different frequencies (daily, weekly or monthly).
And we cannot define at which moment the build is launched (the hour for daily builds or the day of the weekly builds).

Monthly is definitely a too small frequency.
We could move to a weekly build. On a technical point of view, it will not be a problem. Dependencies change very few now (and we could temporary move to a daily build if needed) and build on PR will still be triggered. The main problem is that we would have no more daily build but weekly build.
@kelson42, is it acceptable for you ?

On better solution on middle/long therm would be to reduce the build time by reusing the dependencies archives generated by previous build.
It's a viable solution but I will not do it soon : recurrent builds are building recurrent (daily or weekly) artefacts but also generate dependencies archives for other sub-projects. We need to be sure that archives generated are always up-to-date with last version of dependencies.
To be sure of that, the recurrent builds in travis are building everything from scratch. It's time consuming but it's the easiest to implement.
Using old archives to generate new ones is somehow the opposite of the present solution. If we go in this direction `kiwix-build` need a system to invalidate the cache of previous builds. It is possible but I think we have higher priorities for now.

**Comment by mossroy** [comment]
If you decide to change the frequency, please keep me informed, so that I also modify the kiwix-html5 travis nightly builds accordingly

**Comment by mhutti1** [comment]
I'm not entirely sure but could it be that travis schedules the job to run at the time you initialy set it. So if we reset up the job at another time it would run then?

**Comment by kelson42** [comment]
I prefer to keep nightlies and wait 2 hours for merge request builds.

**Comment by mossroy** [comment]
Maybe an option would be to trigger the nightly builds ourselves.
If we have an API to do that, and Travis does not let us choose the time when a nightly build is started, we might setup a cron on a kiwix server, that starts the nightly build at a time when it might not annoy anybody.
I did not test, but there seems to be such API : https://docs.travis-ci.com/user/triggering-builds/
I agree with @mhutti1 that it was annoying during the hackathon.

**Comment by kelson42** [comment]
The nightlies build now during the night (European Time), is that a good enough workaround?

**Comment by kelson42** [comment]
good enough for @mhutti1
