### ISSUE TITLE
Building with optimizing compilation options

### ISSUE THREAD

**Issue by veloman-yunkan** [kiwix/kiwix-build#463]
I am not sure where to ask this question because it seems to equally apply to all kiwix c++ projects (libzim, zim-tools, kiwix-lib, kiwix-tools). The libraries and binaries in those projects by default are compiled in debug mode without optimization enabled.
This is also true for the artifacts produced by the kiwix-build Release&Nightly jobs.

For performance critical applications significant speed-up can be easily achieved most of the time by simply enabling optimized compilation. Are we going to take advantage of that?

**Comment by mgautierfr** [comment]
This is already the case. If not this is a bug.

We are detecting if we are building a release or a nightly in [.github/scripts/build_release_nightly.py](https://github.com/kiwix/kiwix-build/blob/master/.github/scripts/build_release_nightly.py#L28-L31)
If we are building a release we pass the option `--make-release` to kiwix-build itself.
Then, for all meson project, we pass the options [`--buildtype=release --strip`](`https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/base.py#L459-L465`)

Then meson itself configure to project accordingly (https://mesonbuild.com/Builtin-options.html#core-options)

All our other "external" dependencies and kiwix-desktop are build with `-O3` in CFLAGS and CXXFLAGS (https://github.com/kiwix/kiwix-build/blob/master/kiwixbuild/dependencies/base.py#L312-L315) whatever we build a release or not.

What make you think we don't compile with optimized options ?

**Comment by veloman-yunkan** [comment]
> What make you think we don't compile with optimized options ?

My own ignorance. I never used the `--make-release` option of `kiwix-build` and/or `--buildtype=release` option of `meson`. Thus all benchmarks in my performance improvement PRs were performed using a debug build, which makes little sense. From now on I will build code for benchmarking in release mode.
