### ISSUE TITLE
Publish libzim binaries for windows

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#466]
Like we do for macOS and GNU/Linux

**Comment by kelson42** [comment]
* natively compiled with Microsoft toolchain
* With full creator/xapian support.

**Comment by j0hnm4r5** [comment]
@kelson42 any updates with this one? Is there anything I can do to help?

**Comment by kelson42** [comment]
@j0hnm4r5 Not yet, but should be a matter of days
@mgautierfr Still not available, either static `.lib` nor dynamic `.dll`, see https://download.openzim.org/nightly/2024-08-21/libzim_win-x86_64-2024-08-21.tar.gz

**Comment by kelson42** [comment]
Still not there https://download.openzim.org/nightly/2024-07-24/

**Comment by mgautierfr** [comment]
It's there now : https://download.openzim.org/nightly/2024-08-27/libzim_win-x86_64-2024-08-27.zip

**Comment by kelson42** [comment]
> Will libzim be available for Windows on pip, too? It still says "Platform Windows/AMD64 is not supported" when the "pip install libzim" command is run on Windows. Adding the "--pre" parameter also didn't help. Can we install it by using other parameters?

@samvan11 We are working on it this week, see https://github.com/openzim/python-libzim/issues/91
