### ISSUE TITLE
Kiwix will not install on rpi 4 running raspbian

### ISSUE THREAD

**Issue by samk192** [kiwix/kiwix-build#488]
I'm not sore why my last issue was listed as duplicate and closed.  I have been trying anything I can find to get kiwix to work properly. The only thing I have found to give me any hope whatsoever is SKIP_BIG_MEMORY_TEST=1. However I have no idea how to implement this fix, and I can find no documentation on how to do so. I have been fighting this for about a month and I am beyond frustrated with Linux as a whole. Can anyone point me in the direction of some decent training so I can troubleshoot myself or an actual fix? As stated before, I know NOTHING about Linux or it's terminal commands. PLEASE someone help me with this issue!!  I know next to nothing when it comes to terminal commands and must google and try commands at random and see if anything magically works.  I don't even know what logs to add to this post.  If it helps, I'm pretty sure ninja-ide isn't installed either.  Hopefully the attached terminal output will help.

pi@raspberrypi:~ $ pip install requirements.txt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement requirements.txt (from versions: none)
ERROR: No matching distribution found for requirements.txt
pi@raspberrypi:~ $ kiwix-build --target native_static
ERROR: The target platform native_static cannot be build on host raspbian.
Select another target platform or change your host system.
[INSTALL PACKAGES]
SKIP, No package to install.
[SETUP PLATFORMS]
[PREPARE]
prepare sources pugixml :
  download pugixml : SKIP
  extract pugixml : SKIP
  patch pugixml : SKIP
prepare sources lzma :
  download lzma : SKIP
  extract lzma : SKIP
prepare sources zstd :
  download zstd : SKIP
  extract zstd : SKIP
  patch zstd : SKIP
prepare sources zlib :
  download zlib : SKIP
  extract zlib : SKIP
  patch zlib : SKIP
prepare sources uuid :
  download uuid : SKIP
  extract uuid : SKIP
prepare sources xapian-core :
  download xapian-core : SKIP
  extract xapian-core : SKIP
prepare sources icu4c :
  download icu4c : SKIP
  extract icu4c : SKIP
  patch icu4c : SKIP
prepare sources zim-testing-suite :
  download zim-testing-suite : SKIP
  extract zim-testing-suite : SKIP
prepare sources libzim :
  gitupdate libzim : OK (0.8s)
prepare sources libcurl :
  download libcurl : SKIP
  extract libcurl : SKIP
prepare sources libmicrohttpd :
  download libmicrohttpd : SKIP
  extract libmicrohttpd : SKIP
prepare sources mustache :
  download mustache : SKIP
  extract mustache : SKIP
prepare sources kiwix-lib :
  gitupdate kiwix-lib : OK (1.3s)
prepare sources kiwix-tools :
  gitupdate kiwix-tools : OK (1.3s)
[BUILD]
build pugixml (native_static):
  configure pugixml : SKIP
  compile pugixml : SKIP
  test pugixml : SKIP
  install pugixml : SKIP
build lzma (native_static):
  configure lzma : SKIP
  compile lzma : SKIP
  install lzma : SKIP
build zstd (native_static):
  configure zstd : SKIP
  compile zstd : SKIP
  test zstd : SKIP
  install zstd : SKIP
build zlib (native_static):
  pre_build_script zlib : SKIP
  configure zlib : SKIP
  compile zlib : SKIP
  install zlib : SKIP
build uuid (native_static):
  configure uuid : SKIP
  compile uuid : SKIP
  install uuid : SKIP
build xapian-core (native_static):
  configure xapian-core : SKIP
  compile xapian-core : SKIP
  install xapian-core : SKIP
build icu4c (native_static):
  configure icu4c : SKIP
  compile icu4c : SKIP
  install icu4c : SKIP
build zim-testing-suite (native_static):
build libzim (native_static):
  configure libzim : SKIP
  compile libzim : OK (0.1s)
  test libzim : OK (27.6s)
  install libzim : OK (0.8s)
build libcurl (native_static):
  configure libcurl : SKIP
  compile libcurl : SKIP
  install libcurl : SKIP
build libmicrohttpd (native_static):
  configure libmicrohttpd : SKIP
  compile libmicrohttpd : SKIP
  install libmicrohttpd : SKIP
build mustache (native_static):
  copy_header mustache : SKIP
build kiwix-lib (native_static):
  configure kiwix-lib : SKIP
  compile kiwix-lib : ERROR
run command 'ninja -v'
current directory is '/home/pi/BUILD_native_static/kiwix-lib'
env is :
  SHELL : '/bin/bash'
  COLORTERM : 'truecolor'
  XDG_CONFIG_DIRS : '/etc/xdg'
  XDG_SESSION_PATH : '/org/freedesktop/DisplayManager/Session0'
  XDG_MENU_PREFIX : 'lxde-pi-'
  LANGUAGE : 'en_US.UTF-8'
  _LXSESSION_PID : '666'
  SSH_AUTH_SOCK : '/tmp/ssh-BbrAM4GsyET6/agent.666'
  XDG_CONFIG_HOME : '/home/pi/.config'
  DESKTOP_SESSION : 'LXDE-pi'
  SSH_AGENT_PID : '732'
  NO_AT_BRIDGE : '1'
  XDG_SEAT : 'seat0'
  PWD : '/home/pi'
  XDG_SESSION_DESKTOP : 'lightdm-xsession'
  LOGNAME : 'pi'
  QT_QPA_PLATFORMTHEME : 'qt5ct'
  XDG_SESSION_TYPE : 'x11'
  GPG_AGENT_INFO : '/run/user/1000/gnupg/S.gpg-agent:0:1'
  XAUTHORITY : '/home/pi/.Xauthority'
  XDG_GREETER_DATA_DIR : '/var/lib/lightdm/data/pi'
  HOME : '/home/pi'
  LANG : 'en_US.UTF-8'
  LS_COLORS : 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
  XDG_CURRENT_DESKTOP : 'LXDE'
  VTE_VERSION : '5402'
  XDG_SEAT_PATH : '/org/freedesktop/DisplayManager/Seat0'
  XDG_SESSION_CLASS : 'user'
  TERM : 'xterm-256color'
  USER : 'pi'
  DISPLAY : ':0.0'
  SHLVL : '1'
  XDG_VTNR : '7'
  XDG_SESSION_ID : '2'
  XDG_RUNTIME_DIR : '/run/user/1000'
  LC_ALL : 'en_US.UTF-8'
  XDG_DATA_DIRS : '/usr/share/fkms:/usr/local/share:/usr/share/raspi-ui-overrides:/usr/share:/usr/share/gdm:/var/lib/menu-xdg'
  PATH : '/home/pi/BUILD_native_static/INSTALL/bin:/home/pi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/snap/bin'
  GDMSESSION : 'lightdm-xsession'
  SAL_USE_VCLPLUGIN : 'gtk3'
  DBUS_SESSION_BUS_ADDRESS : 'unix:path=/run/user/1000/bus'
  TEXTDOMAIN : 'Linux-PAM'
  _ : '/home/pi/bin/kiwix-build'
  PKG_CONFIG_PATH : ':/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/pkgconfig'
  LD_LIBRARY_PATH : ':/home/pi/BUILD_native_static/INSTALL/lib:/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf'
  QMAKE_CXXFLAGS : '-I/home/pi/BUILD_native_static/INSTALL/include '
  CPPFLAGS : '-I/home/pi/BUILD_native_static/INSTALL/include '
  QMAKE_LFLAGS : '-L/home/pi/BUILD_native_static/INSTALL/lib -L/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf '
  LDFLAGS : '-L/home/pi/BUILD_native_static/INSTALL/lib -L/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf '
[1/1] c++  -o test/server 'test/9f86d08@@server@exe/server.cpp.o' 'test/9f86d08@@server@exe/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.o' 'test/9f86d08@@server@exe/.._subprojects_googletest-release-1.8.1_googletest_src_gtest_main.cc.o' -L/home/pi/BUILD_native_static/INSTALL/lib -L/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group src/libkiwix.a -pthread /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicui18n.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicuuc.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicudata.a -lpthread -lm /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libzim.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/liblzma.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libzstd.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libxapian.a -lrt /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libz.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libuuid.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libpugixml.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libcurl.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libmicrohttpd.a -Wl,--end-group '-Wl,-rpath,$ORIGIN/../src:$ORIGIN' -Wl,-rpath-link,/home/pi/BUILD_native_static/kiwix-lib/src
FAILED: test/server 
c++  -o test/server 'test/9f86d08@@server@exe/server.cpp.o' 'test/9f86d08@@server@exe/.._subprojects_googletest-release-1.8.1_googletest_src_gtest-all.cc.o' 'test/9f86d08@@server@exe/.._subprojects_googletest-release-1.8.1_googletest_src_gtest_main.cc.o' -L/home/pi/BUILD_native_static/INSTALL/lib -L/home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf -Wl,--as-needed -Wl,--no-undefined -Wl,--start-group src/libkiwix.a -pthread /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicui18n.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicuuc.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libicudata.a -lpthread -lm /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libzim.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/liblzma.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libzstd.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libxapian.a -lrt /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libz.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libuuid.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libpugixml.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libcurl.a /home/pi/BUILD_native_static/INSTALL/lib/arm-linux-gnueabihf/libmicrohttpd.a -Wl,--end-group '-Wl,-rpath,$ORIGIN/../src:$ORIGIN' -Wl,-rpath-link,/home/pi/BUILD_native_static/kiwix-lib/src
/usr/bin/ld: src/libkiwix.a(server_request_context.cpp.o): in function `std::__atomic_base<unsigned long long>::operator++(int)':
/usr/include/c++/8/bits/atomic_base.h:514: undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.

Stopping build due to errors
pi@raspberrypi:~ $

**Comment by kelson42** [comment]
It is written here https://github.com/kiwix/kiwix-build/issues/487#issuecomment-860202412 why your ticket has been closed. We don't recommend to try what you are doing if you don't have a proper understand of Linux and compilation.

**Comment by mgautierfr** [comment]
kiwix-desktop depends of QtWebEngine that need to be compiled in 64bits.
On rpi we always compile in 32bits. So it is not possible to run kiwix-desktop on rpi.

You can use however other tools (kiwix-serve).
We don't compile directly on rpi (it could be done, but we've never tested it and we probably don't want to spend time on this).
If you want to compile kiwix-tools yourself, you must cross-compile it (compile on you "normal" linux for rpi and use the build binary on rpi).

If you know NOTHING on linux and command line, don't try to compile kiwix-tools (use https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-3.1.2-5.tar.gz)

**Comment by samk192** [comment]
I'm not attempting to install desktop.  That was attempted once, (as stated it the original message) and never attempted again.  I am unable to get ANYTHING involving kiwix to install or work properly.  This includes kiwix-serve! Mgautierfr- I attempted to install using your link to no avail.  Attached is my terminal readout.  PLEASE do not ignore me! I just need some guidance.

pi@raspberrypi:~ $ sudo apt-get install https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-3.1.2-5.tar.gz
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package https://download.kiwix.org/release/kiwix-tools
E: Couldn't find any package by glob 'https://download.kiwix.org/release/kiwix-tools'
E: Couldn't find any package by regex 'https://download.kiwix.org/release/kiwix-tools'
pi@raspberrypi:~ $

**Comment by mgautierfr** [comment]
This is not a package installable with apt-get.

Then, open a terminal and do :
```
pi@raspberrypi:~ $ wget https://download.kiwix.org/release/kiwix-tools/kiwix-tools_linux-armhf-3.1.2-5.tar.gz # To download the archive (you can simply download the archive with your web browser)
pi@raspberrypi:~ $ tar xf kiwix-tools_linux-armhf-3.1.2-5.tar.gz # To extract the archive (you can use you file browser to do this)
pi@raspberrypi:~ $ cd kiwix-tools-3.1.2-5 # Go in the directory just created when extracting the archive.
pi@raspberrypi:~ $ chmod u+x kiwix-serve # To make the binary executable
pi@raspberrypi:~ $ ./kiwix-serve -p 8080 <a path to one zim file you have already downloaded> # Launch kiwix-serve using port 8080.
```

Do not close your terminal and, with your we bbrowser, go to address `http://localhost:8080`.

**Comment by samk192** [comment]
mgautierfr- Thank you, thank you, thank you!!!  I got it up and running with all of my zim files.  I couldn't have figured it out without your knowledge and assistance.  Thanks again!
