### ISSUE TITLE
kiwix-build.py should detect early if a dependency (svn for example) is not available (and complain)

### ISSUE THREAD

**Issue by anarcat** [kiwix/kiwix-build#49]
on a fresh new Debian stretch install, I followed the instructions of this readme and Kiwix failed to compile because SVN was missing. it should detect that and just install subversion through `apt-get install subversion`.

(similarly, why aren't meson and ninja installed that way? just `apt-get install meson` was enough here...)

**Comment by kelson42** [comment]
@mgautierfr I had the same "problem" with subversion. I agree with @anarcat that it should be just checked at the beginning an reported properly.

@anarcat for ninja and meson, I agree with you that this is a bit annoying to have to install both of them manually. So far, we have do to so, as we need pretty recent version of them. AFAIK, next Debian stable will be OK.

**Comment by kelson42** [comment]
There is also a ticket to improve a bit the README https://github.com/kiwix/kiwix-build/issues/3. Will work on this.

**Comment by ynikitenko** [comment]
I agree with this proposal. I had a similar issue with `qmake`. Probably I reported that elsewhere, but I forgot or lost the link. I'm not sure whether it's good to comment on this closed issue, but maybe I shall not open a new one (I already opened several ones today).
