### ISSUE TITLE
No Kiwix-Desktop in nightly anymore at all after migrating to Qt 5.15

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#491]
See https://download.kiwix.org/nightly/2021-06-25/

**Comment by kelson42** [comment]
And the Windows build, seems to fail https://github.com/kiwix/kiwix-desktop/issues/658#issuecomment-870305855

**Comment by kelson42** [comment]
We still have errors https://github.com/kiwix/kiwix-build/actions/runs/984712658. Flatpak is still not available.

**Comment by mgautierfr** [comment]
Fixed. Last appimage is available here : https://download.kiwix.org/nightly/2021-06-30/kiwix-desktop_x86_64_2021-06-30.appimage
