### ISSUE TITLE
Be ready to move the macos CI to macOS-11

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#497]
The github macos environment will move to macOS-11 soon (https://github.com/actions/virtual-environments/issues/4060)

We have to check our CI will still work (or at least be prepare to debug when the switch is effective and CI doesn't compile).

From what I see it seems it should work. But the comment https://github.com/actions/virtual-environments/issues/4060#issuecomment-922368258 is a bit disturbing for me.

@automactic, what do you think about this ? Do we have to change things on our side ?

**Comment by automactic** [comment]
I haven't tested building with iOS 15 sdk so I can't really tell you until I try it out

**Comment by kelson42** [comment]
@mgautierfr @automactic What should we do with this ticket? Does something has moved either on one side or the other?

**Comment by kelson42** [comment]
MIght that be that is already moved because we use `macos-latest` ? https://github.com/kiwix/kiwix-build/blob/master/.github/workflows/ci.yml#L164

**Comment by rgaudin** [comment]
Yes, both workflows uses `macos-latest` which currently is `macos-11`.
