### ISSUE TITLE
Meson encountered an error in file meson.build, line 39, column 4:

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-build#5]
Error encountered: For custom ctpp2_prefix_install you need a meson version >=0.31.0

root@deb9-demo:/opt/tools/kiwix-build# meson -v
0.37.1

**Comment by mgautierfr** [comment]
This should have been fixed with kiwix/kiwix-lib@5a9fd26 and kiwix/kiwix-tools@e8dc6b0
