### ISSUE TITLE
Compiling kiwix-build for Raspberry Pi OS 64-bit

### ISSUE THREAD

**Issue by sorjon02** [kiwix/kiwix-build#518]
Hello,
I'm trying to compile the kiwix-build tools for a Raspberry 4 running the new 64-bit version of Raspberry Pi OS. I'm using the command "kiwix-build kiwix-tools > build.log.
Alas I get an error message, as you can see at the end of the log file.
[build.log](https://github.com/kiwix/kiwix-build/files/8104174/build.log)

I attached the compile log. Im not familiar with your buildf tools, so can you please examine the log and give me some advice.
I will be happy to create and upload a 64-bit version of the kiwix-tools for you if you like it.
Best regards,
Sören Jonssson
Sweden

**Comment by kelson42** [comment]
@sorjon02 Have you tried the binaries we distribute? http://download.kiwix.org/release/kiwix-tools/

**Comment by kelson42** [comment]
No feedback, closing.
