### ISSUE TITLE
[CI] Timeout on macos_mixed install_name_tool

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#519]
At the end of the CI process, on macos mixed, we call `install_name_tool` to change the id of the library.
But somehow, the process hangout and the build is cancelled by github
See https://github.com/kiwix/kiwix-build/runs/5268088896?check_suite_focus=true

I don't know why. Maybe @automactic has an idea.

**Comment by kelson42** [comment]
@automactic Could you please help here, each day the system complains because of the broken macOS compilation.

**Comment by mgautierfr** [comment]
@automactic Have you a idea of what going on here ?
This prevent us to build release version of libzim for macos (see https://github.com/kiwix/kiwix-build/runs/6323100414?check_suite_focus=true)

Surprisingly, the `CI` workflow fails at the same point but with a different message https://github.com/kiwix/kiwix-build/runs/6344697226?check_suite_focus=true :
> error: The specified item could not be found in the keychain.

Where the `Release&Nightly` fails with a timeout without message.
