### ISSUE TITLE
Windows CI build release from main branch

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#521]
On appveyor, the CI always build on the master branch of our projects.
This is somehow ok if we build the releases just doing the releases but if it fundamentally wrong, we must build from tags.

This can be forced with specific commit as https://github.com/kiwix/kiwix-build/commit/8f31358810d69c62d852e27ab25c64a048dcc365 but it is "one shoot" commit and those kind of commit cannot be merged in master as it would force the nightly to build from the tags and not from master.

This issue would be fixed by https://github.com/kiwix/kiwix-build/issues/425 as github CI already use a a system to detect we build a release and checkout the correct code.

**Comment by kelson42** [comment]
@mgautierfr We shoukd just move to github actions and let it work like for the others right?

**Comment by mgautierfr** [comment]
Yes

**Comment by kelson42** [comment]
@mgautierfr This issue needs an update, we have no PR linked!

**Comment by mgautierfr** [comment]
This is a appveyor issue. CI using github CI (and so kiwix-build) is ok.
This issue will be fixed by removing AppVeyor CI in favor of github one.
