### ISSUE TITLE
macOS: error when build kiwix-tools natively

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#53]
kiwix-build stopped when building kiwix-tools, seems to sdo with `-lrt`. I am building using `apple-platforms` branch.

The log is here: 
[log.txt](https://github.com/kiwix/kiwix-build/files/1089402/log.txt)

**Comment by mgautierfr** [comment]
I think this is related to the patch here : https://github.com/kiwix/kiwix-build/blob/master/patches/xapian_pkgconfig.patch

I apply this patch on xapian to add the `-lrt` option in xapian.pc in xapian is using the librt.
I had few difficulty to write this patch to correctly define if we are using librt and if we need to add the option. My first idea is that the patch is not well written enough and it breaks somehow on macos.

But it is just a guess, maybe you need `-lrt` and there is a bug somewhere else who prevent the linker to found the lib.

A first thing you can try, is to add some `echo` in xapian's `configure` itself (or `configure.ac`and regenerate configure) to see what is the value of `ac_res` (some how around the line corresponding to the line 29 of the patch)

**Comment by automactic** [comment]
@mgautierfr Sorry I don't know what to do. I could find the place similar to line 29 of the patch in `configure.ac`, but I have no idea how to modify `configure.ac` to echo value of `ac_res`.

BTW, could you please check if my rebase is done correctly? Thanks.

**Comment by kelson42** [comment]
@mgautierfr @automactic Is that ticket still valid? Even if this is still not perfect, I think a lot of progress has been done meanwhile on OSX (cross-) compilation!?

**Comment by kelson42** [comment]
No feedback, assuming problem has been solved.
