### ISSUE TITLE
Build project on Alpine in the CI (as we do for other arch/distrib)

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#537]
PR https://github.com/kiwix/kiwix-build/pull/536 make kiwix-build create the docker compilation image for Alpine.
kiwix-build should also build project on alpine everyday (even if we don't publish it)

**Comment by kelson42** [comment]
@mgautierfr @rgaudin We build now libzim on/for alpine. Do we need to do more?

**Comment by kelson42** [comment]
@rgaudin @mgautierfr We build now libzim on Alpine. Should we do more?

**Comment by mgautierfr** [comment]
I think we are ok here. We have nothing more in mind.
