### ISSUE TITLE
macOS libzim 8.0.0 improperly signed

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#538]
Due to a mistake of mine, the Apple code signing certificate in the secrets was not the one we should be using for signing Mac apps.

This resulted in 8.0.0 release (and nightlies before that) to fail notarization.

Secrets have been fixed but a new build/release is necessary to upload a properly signed libzim an re-request notarization

**Comment by mgautierfr** [comment]
A rebuild on the CI has been done. It should be ok (since few weeks already). Please reopen if I'm wrong.
