### ISSUE TITLE
Publish libzim for arm64

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#549]
In order to provide pylibzim for arm64 (required for https://github.com/offspot/container-images/issues/15), we should publish a release of libzim for arm64 (and probably arm).

**Comment by kelson42** [comment]
@mgautierfr How much work would that be?

**Comment by kelson42** [comment]
After discussion, we want to release/build binaries of libzim:
* aarch64-linux-musl (Alpine based container for RPI)
* aarch64-linux-libc (Linux PC)

**Comment by kelson42** [comment]
See also #537, not sure about the kind of dependence between the two tickets.

**Comment by kelson42** [comment]
And also for macOS Apple M1, but depends on https://github.com/github/roadmap/issues/528
