### ISSUE TITLE
How should I implement iOS sdk Toolchain if no download is necessary

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#55]
As the discussion between @kelson42  and me, it might be a good idea to simultaneously start cross-platform build development for iOS. So in branch `apple_platforms`, I have added iOS SDK class
```
class iOS_sdk(Toolchain):
    pass
```

But different from android, kiwix-build do not need to download the SDK, since it is already part of `Xcode.app`. I just need to run `xcodebuild -version -sdk iphonesimulator | grep -E '^Path' | sed 's/Path: //'` to get the SDK path. How should I implement this class?

**Comment by mgautierfr** [comment]
Like the `mingw32_toolchain`. You just have to not set the inner `Source` class (and neither the `Builder` class)
