### ISSUE TITLE
Wasm libzim package should include precompiled library.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#552]
Until now, precompiled libzim packages include `libzim.so`.
This `libzim.so` include its dependencies as it is linked statically with them.

But on wasm it seems it is not the case. So we have to:
- Check how wasm's `libzim.a` could be linked statically with dependencies (if possible) or
- Include dependencies `.a` in the package

**Comment by Jaifroid** [comment]
Do you mean the way the dependencies are linked in https://github.com/openzim/javascript-libzim/blob/master/Makefile#L42  to make `libzim.a`? If the `libzim.a` produced here contains those dependencies, then it should simply be a matter of compiling it with the JS wrapper using `em++` on openzim/javascript-libzim. However, it's not working, see post below.

**Comment by mgautierfr** [comment]
> Do you mean the way the dependencies are linked in [openzim/javascript-libzim@master/Makefile#L42](https://github.com/openzim/javascript-libzim/blob/master/Makefile?rgh-link-date=2022-11-29T21%3A38%3A40Z#L42) to make libzim.a? 

The pointed line say to make that it need to build other dependencies before building `libzim.a`.
It is "just" an ordering instruction.
The fact that `libzim.a` actually need other dependencies is independent of that.
`kiwix-build` already does that (ordering builds).

> If the libzim.a produced here contains those dependencies, then it should simply be a matter of compiling it with the JS wrapper using em++ on openzim/javascript-libzim. However, it's not working, see post in https://github.com/kiwix/kiwix-build/pull/548#issuecomment-1331357883.

`libzim.a` doesn't contains those dependencies (both with kiwix-build and javascript-libzim's makefile).
This is why you specify all the dependencies at compilation of demo_file_api.cpp here : https://github.com/openzim/javascript-libzim/blob/master/Makefile#L52

This issue is about either make `libzim.a` contains those dependencies or package the dependencies along with `libzim.a`.
I will probably do the latter.

**Comment by Jaifroid** [comment]
OK, thanks @mgautierfr. That sounds good. When you have a `libzim.a` with dependencies built in, I'll be very happy to test compiling it to WASM + bindings with Emscripten, and then test the WASM itself in our test implementation. It should then be relatively easy to integrate this `libzim.a` binary into a nightly CI at openzim/javascript-libzim.
