### ISSUE TITLE
Consider changing the internal `lib` directory of WASM release from `x86-64-linux-gnu` to `wasm`

### ISSUE THREAD

**Issue by Jaifroid** [kiwix/kiwix-build#556]
This arises out of a comment originally posted in: https://github.com/openzim/libzim/issues/751#issuecomment-1340518968:

> Why do we have a CPU architecture `x86_64-linux-gnu` inside the `lib` directory, when wasm is its own "architecture", and the wasm should work on any CPU? Wouldn't it make more sense for it to be called `wasm`, or not to have a subdirectory and merely include all the binaries inside `lib`? It seems to me that the designation `x86_64` is a bit misleading.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/4304337/206115234-ef09f118-4f45-4bb2-999b-9a2453ec3e55.png">

As an alternative, maybe there is no need for a directory inside the `lib` directory. The dependencies could all be directly inside `lib`.

**Comment by Jaifroid** [comment]
@kelson42 Just wondering if changes to https://github.com/kiwix/kiwix-build/commit/b9400e8fd1a811a1c7f21ac36d5b2f14aa7a9444 has caused the[ compilation failure with the WASM](https://github.com/kiwix/kiwix-build/actions/runs/4248577129/jobs/7387902990) in CI last night?

**Comment by Jaifroid** [comment]
Ah, OK. I noticed the build failed (because it caused javascript-libzim to fail), came here and saw a push but didn't check if the PR was merged. Clearly must be something else. For whatever reason, it's just the WASM build that appears to be failing.

**Comment by Jaifroid** [comment]
OK, thanks, so I need to change the compilation process over at javascript-libzim? It's a minor change, but I'll probably wait till a first nightly has this (and fails compilation to JS + WASM).

**Comment by kelson42** [comment]
We should probably plan a release?

**Comment by Jaifroid** [comment]
I think we (I) should deal with nightlies first, making sure everything is working on javascript-libzim, then once all is OK, it would be good to have a new official release here (and corresponding release from javascript-libzim).

**Comment by Jaifroid** [comment]
@kelson42 @mgautierfr Apologies if I'm missing something, but the latest nightlies don't contain `libzim.a` or the `lib` folder mentioned in #569. For example, looking in `https://download.openzim.org/nightly/2023-03-10/libzim_wasm-emscripten-2023-03-10.tar.gz`, all I see is as in screenshot below. No `lib` directory and no `libzim.a`.

![image](https://user-images.githubusercontent.com/4304337/224490265-a0021bf2-862c-4678-8531-af18ba8a97bc.png)

**Comment by Jaifroid** [comment]
More pertinently, this is what is in base directory of archive. If I'm not mistaken there should also be a `lib` directory:

![image](https://user-images.githubusercontent.com/4304337/224490526-3801b9f3-8e7a-4771-b138-459774f8f1b4.png)

**Comment by Jaifroid** [comment]
Same issue with `libzim_wasm-emscripten-2023-03-13.tar.gz`, so it's not just transitory.

**Comment by Jaifroid** [comment]
@kelson42 This is still broken in `libzim_wasm-emscripten-2023-03-15.tar.gz`. There is only an `includes` directory, no directory with the libzim binary. I suspect #569 did not take into account some aspect of the binary build process? Any thoughts as to why the libzim.a isn't being included?

**Comment by kelson42** [comment]
@Jaifroid AFAIK @mgautierfr is working in this ticket. I don't have more details.

**Comment by Jaifroid** [comment]
@mgautierfr Many thanks for fixing that 🎉. I confirm it's now working for nightly builds, and I have merged the PR fixing https://github.com/openzim/javascript-libzim/issues/44.

In order for releases to work, we'll need a new release of libzim in due course.

😊
