### ISSUE TITLE
Would it be a good idea to split kiwix-build.py into multiple files?

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#56]
Currently `kiwix-build.py` is too huge, I find it hard to navigate. And I cannot put work on different classes in different commits. (i.e. if I added something to both `iOS_sdk` and `iOSTargetInfo`, I have to commit them together)

I think it would be a better idea to separate them into files like `TargetInfo.py`, `Toolchain.py`, etc.

**Comment by mgautierfr** [comment]
> Currently kiwix-build.py is too huge, I find it hard to navigate

Yes, definitively. Even for me it's sometime to big :)

> And I cannot put work on different classes in different commits. (i.e. if I added something to both iOS_sdk and iOSTargetInfo, I have to commit them together)

But yes, you can. You don't have to `add` all the change of a file in git. You can only add a "chunk" of change. (With `git gui` or `git add -p`)

Do you want I start to split it right now or do you prefer to merge you `apple_platforms` branch before (and avoid complex rebase) ?
(BTW, Your last rebase is good)

**Comment by automactic** [comment]
let me merge first

**Comment by automactic** [comment]
@mgautierfr, it would be really great if you could finish separating `kiwix-build.py` into small files as soon as possible. It's gonna help me a lot.

If you are too busy. I could also do it. It would help me understand the project better.

**Comment by mgautierfr** [comment]
I've merge the PR #62.

> If you are too busy. I could also do it. It would help me understand the project better.

Yes, please. I will not have a lot of time before a while. It would be nice, if you can do the split.
And indeed, it will help you understand the project. And more people understand the project, the better it is.

Do not hesitate to ask if you need further details.

**Comment by mgautierfr** [comment]
Kiwx-build is now  pretty well separated in different files. I'm closing.
