### ISSUE TITLE
Publish libzim on arm64 musl

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#585]
Wanted target is :
* aarch64-linux-musl (Alpine based container for RPI)
* For testing purposes we need as well x86-64 with musl

See https://github.com/kiwix/kiwix-build/issues/549#issuecomment-1317348275

**Comment by rgaudin** [comment]
Since 8.2.1, we have [`aarch64-musl`](https://download.openzim.org/release/libzim/libzim_linux-aarch64-musl-8.2.1.tar.gz) binary so this is done but we need `x86_64-musl` as well so I'll leave it open

**Comment by kelson42** [comment]
@mgautierfr any update here? We kind of wait on this to release next python-libzim.
