### ISSUE TITLE
zim-tools should be published on macOS ARM

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#593]

**Comment by mgautierfr** [comment]
For now zim-tools doesn't compile of macOS_arm_static as meson doesn't find libmagic.
Maybe related to https://github.com/openzim/zim-tools/issues/344

**Comment by rgaudin** [comment]
Do you have more details? Do you know what meson is looking for? @fledgeXu uses an arm64 macOS and certainly has a functioning libmagic as it's used by scraperlib.

**Comment by mgautierfr** [comment]
https://github.com/kiwix/kiwix-build/pull/624 seems to fix the issue. 
@rgaudin can you test https://tmp.kiwix.org/ci/dev_preview/zim-tools_macOS_arm/zim-tools_macos-arm64-2023-06-12.tar.gz ?

**Comment by FledgeXu** [comment]
I just tested it.
`zimdump` and `zimsplit` are still broken. Here is the log:
```
❯ ./zimdump
dyld[12475]: Library not loaded: @rpath/libdocopt.dylib
  Referenced from: <29FB06CF-F024-319E-ADCA-001EADE493D7> /Users/fledge/Downloads/zim-tools_macos-arm64-2023-06-12/zimdump
  Reason: tried: '/usr/local/lib/libdocopt.dylib' (no such file), '/usr/lib/libdocopt.dylib' (no such file, not in dyld cache)
zsh: abort      ./zimdump
```
```
❯ ./zimsplit
dyld[12571]: Library not loaded: @rpath/libdocopt.dylib
  Referenced from: <F6C57745-5824-3900-9C5D-81C2CA65C978> /Users/fledge/Downloads/zim-tools_macos-arm64-2023-06-12/zimsplit
  Reason: tried: '/usr/local/lib/libdocopt.dylib' (no such file), '/usr/lib/libdocopt.dylib' (no such file, not in dyld cache)
zsh: abort      ./zimsplit
```

**Comment by mgautierfr** [comment]
Hum...

From https://tmp.kiwix.org/ci/fail_log_macos_macOS_arm64_static.tar.gz (which was a upload of fail compilation before [`5a86f83` (#624)](https://github.com/kiwix/kiwix-build/pull/624/commits/5a86f83deb365e6239cef7199489139873083e42), but configuration step is the same), we have this : 
`Rejected /Users/runner/BUILD_macOS_arm64_static/INSTALL/lib/libdocopt.a, supports ['aarch64'] but need arm64`

I suspect some inconsistency in https://github.com/kiwix/kiwix-build/blob/main/kiwixbuild/platforms/ios.py#L146-L152
but don't know how to solve it (should we have all `aarch64` or `arm64` ?).
Or the error is elsewhere ?

**Comment by kelson42** [comment]
@automactic ping?
