### ISSUE TITLE
Secure all our C++ compiler can deal with C++17

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#598]
We need to have our code been compliant with the C++17 norm (which is something different than using C++17 features). But for that we need first to secure that Kiwix-build uses when possible compilers which support C++17

**Comment by kelson42** [comment]
@mgautierfr Is that ticket implemented meanwhile?

**Comment by mgautierfr** [comment]
Yes, We are now compiling all our projects with C++17.
