### ISSUE TITLE
Add Linux/ARM to CI build targets

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-build#6]
Please include support for arm, especially rpi in builds

**Comment by mgautierfr** [comment]
Ho yes, this is absolutely needed, and more than the cross-compilation for Windows we already have. 
It should be not complicated to add. I will do it in the week.

**Comment by kelson42** [comment]
https://github.com/kiwix/kiwix-tools/issues/13 depends on that ticket

**Comment by mgautierfr** [comment]
Closed with #30

**Comment by kelson42** [comment]
Here is the first ARM nightly build http://download.kiwix.org/nightly/2017-04-29/kiwix-tools_armhf_2017-04-29.tar.gz
