### ISSUE TITLE
Fix win32 cross-compilation when wine is installed on the system.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#601]
On recent fedora (at least) :
- lzma and xapian (and project using meson but we can deactivate it) try to check that binary create by the compiler can be run correctly. (If wine is present) But binary fails to run as they search for library `libgcc_s_dw2-1.dll`. This could be fixed by setting a (wihch one ?) env var to point to the right path or by using `-static-libstdc++`
- `-static-libstdc++` embeds all symbols in the dependency library. So when we do the final link, we have multiple definitions of `_Unwind_Resume`
- Desinstalling `wine` skip the check of the compiler and so we can do the full cross-compilation.
- As we build in static (`win32_static`) we add the `-static-libstdc++` at the end of the process, so it works.

We should fix this correctly to not ask dev to uninstall wine.

(All this message have to be double checked when fixing this issue. Don't trust me on this)

**Comment by kelson42** [comment]
For Windows the supported compilation scenario should be Windows env+cl.exe. Not in favour that we invest anything more in cross-compilation for Windows binaries.

**Comment by mgautierfr** [comment]
I agree.
