### ISSUE TITLE
Libzim releases include the full libicu data

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#603]
… but actually we use only part of it. We should better release libzim only with a subset of it. This would allow to save many MBs is the libzim binary release.

**Comment by mgautierfr** [comment]
What we do for Android is packaging the data as a external file. But we use the same dataset in all our build.
This data set is already patched : https://github.com/kiwix/kiwix-build/blob/main/kiwixbuild/patches/icu4c_custom_data.patch

This may be improved but I don't how/what to remove.
