### ISSUE TITLE
Release native_static on macos fails to trigger workflow.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#605]
See : https://github.com/kiwix/kiwix-build/actions/runs/4829262747/jobs/8604088870

For what I understand, the workflow is already triggered by native_static on linux and shouldn't be trigger by native_static on macos.

@rgaudin do you agree ?

**Comment by rgaudin** [comment]
Exactly. We weren't affected as we were not creating archives for zim-tools and kiwix-tools for macOS before. Code shouldn't have relied on that assumption.

**Comment by kelson42** [comment]
What is the status here?

**Comment by mgautierfr** [comment]
I think it is fixed by https://github.com/kiwix/kiwix-build/pull/630/commits/7e9a145bc54c0b024d6fe9e0f1fb083cc626b52b

**Comment by kelson42** [comment]
@mgautierfr If good for you and @rgaudin, good for me :)

**Comment by rgaudin** [comment]
I also believe it's fixed.
