### ISSUE TITLE
Last publication of kiwix-tools seems to not work on raspberryPi

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#613]
See https://github.com/iiab/iiab/issues/3574

This is probably due to our change of toolschain used to compile for armhf and aarch64. (#580)

**Comment by holta** [comment]
> `kiwix-serve` starts correctly on armhf (using qemu) but crash of first request.

Also, on some Raspberry Pi's (e.g. 32-bit Raspberry Pi Zero W) `kiwix-serve` no longer starts at all:

- https://github.com/iiab/iiab/issues/3574#issuecomment-1546784506

Recap: `kiwix-serve --version` works with 3.4.0, but with 3.5.0 it responds `Illegal instruction`

**Comment by kelson42** [comment]
Serious! PRIO0

**Comment by sakshi0444** [comment]
Hello! I want to make changes in this repo kindly allow me to do so by sharing the source code. thank you.

**Comment by kelson42** [comment]
@sakshi0444 Please use your own fork and do PR from there
@holta Kind reminder
@mgautierfr I'm in favour to merge if no feedback in the next 24 hours.
