### ISSUE TITLE
Use libxapian 1.4.23

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#627]
https://trac.xapian.org/wiki/ReleaseOverview/1.4.23

We shoudl be able to avoid https://github.com/kiwix/kiwix-build/pull/600/commits/5ef7e2a017dcfcfeb10ad376e9a8dcb5d7a37812#diff-195a8c5ae0484fec5d4b6a682644710a05e8756754472b73f44f7bca09993ad0R17

**Comment by asryan11** [comment]
Hello, is this issue still open?

**Comment by mgautierfr** [comment]
This is still open yes. Do you want to do it ?

**Comment by asryan11** [comment]
Yes, I want to do this. But I am new to open source can you just guide me on how to complete this or tell me where to start?

**Comment by dilankavishka** [comment]
Can i work on this issue plaese?

**Comment by dilankavishka** [comment]
please assign me to this issue

**Comment by kshitiz305** [comment]
Which line do you wish to avoid in this .

**Comment by mgautierfr** [comment]
By updating libxapian version, we should not need to have a custom patch.

If you (any of you) want to do it, simply do it and propose a PR.
Don't ask how to do it, I would spend less time doing it myself :)
