### ISSUE TITLE
Incorrect docker trigger on macOS

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#629]
In recent release (3.5.0-2 and alike), macos(native_static) failed trying to trigger the zim-tools docker workflow.
This action fails because the `GHCR_TOKEN` secret is not passed to the `Macos` job nor the `Build release` step.

Currently, this workflow is triggered:
- if it's a release
- if there's an archive
- only for zim-tools and kiwix-tools

It's all OK but it means that every platform attempts to trigger this workflow while we should ideally only trigger it once.
If we control the order, we'd ideally trigger it at the end. At least at the end of the linux ones as the docker images uses the uploaded linux binaries.

https://github.com/kiwix/kiwix-build/blob/1fde377a3464b8d22eebcb016a428c67393e9324/.github/scripts/build_release_nightly.py#L34-L46

- [ ] Decide where it'd be best to call it
- [ ] Update build_release_nightly accordingly
- [ ] Rename kiwix-build action secret `GHCR_TOKEN` to `GITHUB_PAT` (more appropriate) and update the worflow to use it
- [ ] Re-run the release for the missing archives (kiwix-tools macOS)

**Comment by mgautierfr** [comment]
I have taken the liberty to partly fix this issue with #630 

We would trigger the docker workflow only for context where we have a `D`(ocker) in the build definition.
