### ISSUE TITLE
Update ICU to a more recent version.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#644]
Following https://github.com/openzim/javascript-libzim/issues/58 we have to update ICU to a more recent version.

ICU is a tricky part :
- We patch the ICU data to put "only what we need".
- To patch it, we need to use the svn version, not the released sources.
- We package differently the data depending of the platform.
- On android, it is the application itself which contains the data and load it for us before using libzim/libkiwix.

All those things was made on long time ago. We probably better have to question all of this instead of blindly do the same thing.

**Comment by kelson42** [comment]
From my side, requirements are:
* data should be available and loadable separatly (to avoid duplicates - obe per arch - in Android bundle).
* data should be minimal to avoid waste od space/bandwidth
* Most use cases should have the data in the binaries
* We should fo our best to avoid code patching

**Comment by kelson42** [comment]
Fixed by #642
