### ISSUE TITLE
Why compiling libkiwix for iOS/macOS does embeds the libzim?

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#647]
With:
kiwix-build --target-platform iOS_arm64 libkiwix

I thought that now the two libraries should be handled separatly. So we should have IMO:
* kiwix-build --target-platform iOS_arm64 libkiwix AND
* kiwix-build --target-platform iOS_arm64 libzim ?!

**Comment by mgautierfr** [comment]
Why do you think that libkiwix embeds libzim ?

The only reason why you may find libzim symbol in libkiwix is because we compile libraries in static mode. So potentially libzim symbols used by libkiwix are statically linked in libkiwix.

**Comment by kelson42** [comment]
@rgaudin told me and the README on kiwix/apple says nothing about compiling the libzim!

**Comment by rgaudin** [comment]
As I said, libkiwix in kiwix-build automatically triggers a libzim build as libzim is considered a dependency.
@kelson42 tells me that libkiwix doesn't depend on libzim anymore (as it doesn't wrap it anymore) and thus should not be automatically built when building libkiwix.

At least that's what I understood but all those comments are confusing :)

**Comment by mgautierfr** [comment]
What we had removed from libkiwix is the API to read article in zim files (https://github.com/kiwix/libkiwix/pull/789). This means that if you want to read content in a zim files you must use libzim API (and so, directly depend on it).

But libkiwix still need to read in libzim (for itself). At least for:
- server (libkiwix need to access the content in a zim file to serve it)
- library management (update a book from a zim file, access metadata)
- allow you to access a zim file (we will open a `zim::Archive` for you and return it to you, handling cache and so).

So:
- Libzim IS a dependency of libkiwix.
- User need to have a explicit dependency to libzim if they want to read content in zim file.
  (Telling that, you don't need it if you just want to spawn a server and just manage a library)

**Comment by rgaudin** [comment]
OK, that's very clear.

**Comment by kelson42** [comment]
@rgaudin Does it implies changes in the xcframework or can we just close this ticket?

**Comment by rgaudin** [comment]
We can close.
