### ISSUE TITLE
Wrap XCFramework into a swift package, for Apple (iOS, macOS) distribution

### ISSUE THREAD

**Issue by BPerlakiH** [kiwix/kiwix-build#671]
Importing / adding the libkiwix library into iOS and macOS application could become a lot easier, by providing a swift package, which is a folder structure + manifest file that is wrapping up the current XCFramework output.

Details / how to can be found here:
https://blog.devgenius.io/xcframework-swiftpackagemanager-c03f4b1903d9
https://developer.apple.com/documentation/xcode/distributing-binary-frameworks-as-swift-packages

**Comment by kelson42** [comment]
It's important we use this opportunity to rename the whole package to "libkiwix" to be coherent with the rest.

**Comment by BPerlakiH** [comment]
We have tried the following setups:
- creating an SPM with `.binaryTarget` pointing to a remote zip (of the libkiwix framework), containing the module mapping headers
- creating an SPM locally with `.binaryTarget` wrapping a local copy of the libkiwix framework, containing the module mapping
Non of the above seemed to compile properly with the main project.
One suspicion, why this is, that SPM is not yet supporting cross language bridging (C++ / Objective-C) yet. 
There are swift community requests for this feature: 
- https://github.com/apple/swift-package-manager/blob/main/Documentation/Design/PackageManagerCommunityProposal.md#system-library-access-with-module-maps
- https://github.com/apple/swift-package-manager/blob/main/Documentation/Design/PackageManagerCommunityProposal.md#support-for-other-languages

For these reasons we have decided not to use Swift Package Manager for integrating our XCFramework, as it is not yet fully supported in it's current form.

**Comment by kelson42** [comment]
I will keep the ticket open, this will be reassesed in a year.

**Comment by kelson42** [comment]
@rgaudin @BPerlakiH A year as almost pass. Do you think this would still make sense to implement this?

**Comment by rgaudin** [comment]
I think that should it be possible, it's nice to have but I don't think it's worth the effort.

**Comment by kelson42** [comment]
Closing this issue, current solution is "good enough".
