### ISSUE TITLE
Explicit dependence names for macOS

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#677]
Currently with use `native_xyz` for macOS dependencies (filenames) for macOS binaries, but now that we want to compile on both M1 and x86_64, we need to be explicit. Otherwise no clue about what we are talking about and we get "unclear" error message later. See https://github.com/openzim/libzim/pull/856

BTW, target names for Apple platform are in both CI and CD with uppercase, this seems wrong.

**Comment by kelson42** [comment]
@mgautierfr What is the status here?

**Comment by kelson42** [comment]
@mgautierfr Does #689 has fixed this issue?

**Comment by mgautierfr** [comment]
Fixed indeed.
