### ISSUE TITLE
post checksums for AppImage

### ISSUE THREAD

**Issue by jamcinnes2** [kiwix/kiwix-build#683]
Could you post checksums for appimage downloads? sha256sum or whatever you like on a https site.

**Comment by kelson42** [comment]
Each file on download.kiwix.org has already its md5sum check available. Just add « .md5 » to the URL. Here it is http://download.kiwix.org/release/kiwix-desktop/kiwix-desktop_x86_64_2.3.1-4.appimage.md5.
