### ISSUE TITLE
Create a github action to automatically download the right dependency archive in our project CI.

### ISSUE THREAD

**Issue by mgautierfr** [kiwix/kiwix-build#695]
kiwix-build publish archives containing compile dependencies to be use by our project.

For example : `https://tmp.kiwix.org/ci/deps2_focal_aarch64_dyn_libkiwix.tar.xz` is the pre-compiled dependencies for the libkiwix project, build on `focal` to build using the `aarch64_dyn` target (even if `target` doesn't really exist at project level)

On project CI, this archive is downloaded using this kind of [simple script](https://github.com/kiwix/libkiwix/blob/177e1d5da6e4df3ba42c12a957b86ec1c701d331/.github/workflows/ci.yml#L93-L94):
```bash
ARCHIVE_NAME=deps2_${OS_NAME}_${{matrix.target}}_libkiwix.tar.xz
wget -O- http://tmp.kiwix.org/ci/${ARCHIVE_NAME} | tar -xJ -C /home/runner
```

But now kiwix-build publish these archives also for PR in a "dev_preview" directory. (https://github.com/kiwix/kiwix-build/pull/651).
It would be nice that if we have a project PR (using branch `foo`) and a dependency archive exists in `tmp.kiwix.org/ci/dev_preview/foo`, we use this one (and fallback to the "main" archive if not).

We don't want to update and maintain such a script in all our projects. So it is probably time to create a github action which will download and install the right dependencies automatically.

**Comment by kelson42** [comment]
@mgautierfr Is that not what has been done with https://github.com/kiwix/kiwix-build/tree/main/actions/dl_deps_archive ?

**Comment by mgautierfr** [comment]
Yes. It is done.
