### ISSUE TITLE
Build for windows cannot find qt everywhere

### ISSUE THREAD

**Issue by sgourdas** [kiwix/kiwix-build#714]
When running `kiwix-build kiwix-desktop --config win32_static` I get the below error

```
prepare sources qt :
  download qt : Cannot download url http://ftp.oregonstate.edu/.1/blfs/conglomeration/qt5/qt-everywhere-src-5.10.1.tar.xz:
Not Found
ERROR
```

The link seems to be expired or am I doing something wrong?

**Comment by mgautierfr** [comment]
You are not doing something wrong. Qt is pretty difficult to install/compile automatically.
kiwix-build should not try to do it (at least for now, we have some other priority than this).

#720 is fixing that. If kiwix-build don't know how to install it from native packages (rpm/deb) it print a warning telling that you have to install it. (This is the case on Windows).

You have to install Qt (with Qtwebengine module) on your side using Qt official installer.

---

Please not that I'm currently working on the compilation of kiwix-desktop natively on Windows using kiwix-build. For now it is not functional. You may want to follow this work made on PR #719
