### ISSUE TITLE
Alert for "downloading list of catalogs" is not dismissable

### ISSUE THREAD

**Issue by atgomez** [kiwix/kiwix-build#72]
The pop up indicates "do not ask me again," which only registers with the app if you say "yes" and not if you say "no." So you have to dismiss it all the time. (Saw this on Reno's computer at the hackathon)

**Comment by kelson42** [comment]
I confirm.

**Comment by kelson42** [comment]
This issue was moved to kiwix/kiwix-xulrunner#483
