### ISSUE TITLE
[REGRESSION] Kiwix desktop flatpak nightly is missing

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#730]
See https://download.kiwix.org/nightly/2024-08-27/?C=N;O=A

**Comment by mgautierfr** [comment]
It is here https://download.kiwix.org/nightly/2024-08-27/org.kiwix.desktop.2024-08-27.flatpak

**Comment by kelson42** [comment]
Sorry, had forgotten the file name is totally different.
