### ISSUE TITLE
Replace Appveyor by GitHub for Windows CI

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#735]

**Comment by mgautierfr** [comment]
Isn't a duplicate of #425 ?

**Comment by kelson42** [comment]
This ticket asks only for a replacement of the workflow. The other ticket talks as well of a few other things. So the older issue is such an umbrella issue that I guess anything related to windows CI is a duplicate of it. But at this stage this is too late to fix this, so closing this one.
