### ISSUE TITLE
Libzim CD does not publish ZIP/DLL in case of release

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#738]
I just release 9.2.3, but no libzim Windows binaries are published at https://download.openzim.org/release/libzim/

**Comment by kelson42** [comment]
Now available at but ICU DLL are still not included. See https://github.com/openzim/libzim/issues/923

**Comment by mgautierfr** [comment]
They are in bin directory.

**Comment by kelson42** [comment]
@mgautierfr Indeed! I guess we should close this issue.
