### ISSUE TITLE
DLL and dependency libs are not published

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#743]
See https://download.kiwix.org/nightly/2024-08-30/libkiwix_win-i686-2024-08-30.zip, I see only the headers

**Comment by mgautierfr** [comment]
This is not a regression (See https://download.kiwix.org/release/libkiwix/libkiwix_win-i686-12.1.0.zip)

I think this archive is wrongly published.
First of all, it is not publish on release.
Nightly is uploading everything it build (even if not set to be published) and I think we should not.

On top of that, this library is created from static build (which obviously doesn't contain dll)
And it is from cross-compilation from f35, which will be removed.
We would better fix native dynamic compilation on libkiwix and correctly publish it (if we need to publish it as no ask for it until now)

**Comment by kelson42** [comment]
Not a regression indeed. AFAIK we have no usage for these windows binaries. Therefore, either it is published and OK (so with dll) or we stop publishing the whole tarball.
