### ISSUE TITLE
Disable DEBUG for Windows nightly 

### ISSUE THREAD

**Issue by rgaudin** [kiwix/kiwix-build#757]
⚠️ It's at the frontier of bug/feature.

On Windows, binaries `cl`-compiled with `_DEBUG` require the debug version of the runtime libraries (MSVCRT).

Currently, our nightlies use `_DEBUG` and thus require nightly users to install specific development tools to use them.

After discussing it with @kelson42 it appears nightlies main role is to allow power users to test the current state of projects and is not a developer/debug tool.

We should thus remove `_DEBUG` from nightlies.

What it entails is unclear at this stage ; this is in reaction of testing a kiwix-desktop. I dont know the state of shared dependencies.

On kiwix-desktop, at least there is:

```py
        @property
        def make_targets(self):
            if platform.system() == "Windows":
                yield "release-all" if option("make_release") else "debug-all"
            else:
                yield from super().make_targets

        @property
        def make_install_targets(self):
            if platform.system() == "Windows":
                yield "release-install" if option("make_release") else "debug-install"
            else:
                yield "install"
```

**Comment by kelson42** [comment]
@veloman-yunkan This impact I believe all the repositories and make the nightly buiilds almost totally unusable. Do you believe this is easily fixable?

**Comment by kelson42** [comment]
@veloman-yunkan Any news here? I kind of though there was a test version somewhere but can 't find it anymore.

**Comment by veloman-yunkan** [comment]
> On Windows, binaries `cl`-compiled with `_DEBUG` require the debug version of the runtime libraries (MSVCRT).
> 
> Currently, our nightlies use `_DEBUG` and thus require nightly users to install specific development tools to use them.

Can't we address that problem by simply including the debug version of the runtime libraries with the artifacts of the nightly builds?

**Comment by kelson42** [comment]
> > On Windows, binaries `cl`-compiled with `_DEBUG` require the debug version of the runtime libraries (MSVCRT).
> > 
> > Currently, our nightlies use `_DEBUG` and thus require nightly users to install specific development tools to use them.
> 
> Can't we address that problem by simply bundling the debug version of the runtime libraries with the artifacts of the nightly builds? 

I would really like to avoid this.

**Comment by veloman-yunkan** [comment]
> > > On Windows, binaries `cl`-compiled with `_DEBUG` require the debug version of the runtime libraries (MSVCRT).
> > > Currently, our nightlies use `_DEBUG` and thus require nightly users to install specific development tools to use them.
> > 
> > 
> > Can't we address that problem by simply bundling the debug version of the runtime libraries with the artifacts of the nightly builds?
> 
> I would really like to avoid this.

Why? How is this different from bundling other dynamic libraries?

**Comment by rgaudin** [comment]
We are not allowed to do this. It's a licensing issue.

**Comment by kelson42** [comment]
> > > > On Windows, binaries `cl`-compiled with `_DEBUG` require the debug version of the runtime libraries (MSVCRT).
> > > > Currently, our nightlies use `_DEBUG` and thus require nightly users to install specific development tools to use them.
> > > 
> > > 
> > > Can't we address that problem by simply bundling the debug version of the runtime libraries with the artifacts of the nightly builds?
> > 
> > 
> > I would really like to avoid this.
> 
> Why? How is this different from bundling other dynamic libraries?

First of all I don't want to have other libraries in DLL either, we have many issues around this topic. DLL adds a level of hassle and considering we deal with FOSS, we can avoid this.

Then, here we don't need the debig symbols in nightlirs, therefore no reason to conplexify everything for this.
