### ISSUE TITLE
Update kiwix-tools status Windows build wiki

### ISSUE THREAD

**Issue by sgourdas** [kiwix/kiwix-build#760]
> kiwix-tools also exists but is broken.

AFAIK  kiwix-tools cross compilation for Windows is fixed. So we should update the [wiki](https://github.com/kiwix/kiwix-build/wiki/Setup-dev-environment-en-Windows#compile) accordingly.

**Comment by sgourdas** [comment]
@kelson42 I do not have edit rights on it.

**Comment by kelson42** [comment]
@sgourdas I have invited you, you should have the permission then.

**Comment by sgourdas** [comment]
@kelson42 I updated it and also fixed some minor details on the rest of the doc.
