### ISSUE TITLE
Use aria2c 1.37.0 in Kiwix-Desktop Appimage

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#783]
See https://github.com/aria2/aria2/discussions/2136
because of https://github.com/kiwix/kiwix-desktop/issues/809

**Comment by kelson42** [comment]
Actually it seems we already use latest version... but I feel lost as it seemed the release has been made a few weeks ago. Anyway, closing.

**Comment by veloman-yunkan** [comment]
> Actually it seems we already use latest version...

Appimage creation script uses aria2 v1.36: https://github.com/kiwix/kiwix-build/blob/0109c8ced3cdd8a935117ea83066674a53d47d08/scripts/create_kiwix-desktop_appImage.sh#L32-L33

**Comment by kelson42** [comment]
Ok... reopening and I will try to amke a patch to fix ASAP.

**Comment by kelson42** [comment]
@veloman-yunkan I had again a look in detail. It seems indeed that we use the proper/latest version of aria2c everywhere except the appimage.

Beside the fact that this is "hidden" in another file than the usual dedicated Python module, I have remarked that [the 1.37.0 release on GitHub](https://github.com/aria2/aria2/releases/tag/release-1.37.0) does not provide such a binary for Linux.

Beside the fact that we need to compile aria2c statically for LInux (to then include it in the `.appimage`), I would like that this is handled properly in `aria2.py`. Then this would be part of the dependencies files... which could then be downloaded to create properly the appimage.

Does that sound good?

**Comment by kelson42** [comment]
So, original source of binaries has not a binary of aria2c 1.37.0 https://github.com/q3aql/aria2-static-builds/

But I have found an alternative at https://github.com/q3aql/aria2-static-builds/, without properly fixing the problem this might help at least to move forward.

**Comment by veloman-yunkan** [comment]
> but I feel lost as it seemed the release has been made a few weeks ago.

I believe that there is still some confusion here as aria2 1.37 has been released more than a year ago.

**Comment by kelson42** [comment]
> > but I feel lost as it seemed the release has been made a few weeks ago.
> 
> I believe that there is still some confusion here as aria2 1.37 has been released more than a year ago.

Yes, the only confusion is that I shortly believed it has been newly release this year. But the only problem is the appimage. All the rest looks good (beside the fact that we use binaries and don't compile them ourself).
