### ISSUE TITLE
Publishing of 2.4.0 binaries fails

### ISSUE THREAD

**Issue by kelson42** [kiwix/kiwix-build#785]
https://github.com/kiwix/kiwix-build/actions/runs/12331239742

**Comment by kelson42** [comment]
@veloman-yunkan Really strange that CI works, even CD for nightlies... but not release!

**Comment by veloman-yunkan** [comment]
Indeed, `main_project_versions` [has not been updated in PR#784](https://github.com/kiwix/kiwix-build/pull/784/files).

**Comment by veloman-yunkan** [comment]
> Indeed, `main_project_versions` [has not been updated in PR#784](https://github.com/kiwix/kiwix-build/pull/784/files).

That probably explains the build failures both in https://github.com/kiwix/kiwix-build/actions/runs/12331239742 (this ticket) and https://github.com/kiwix/kiwix-desktop/actions/runs/12331074751 (kiwix/kiwix-desktop#1285) - trying to make a new major release of `kiwix-desktop` using the source code of the old major release is not a good idea.

**Comment by veloman-yunkan** [comment]
Though looking again at the error in kiwix/kiwix-desktop#1285 I have to admit that there may be a different error there.

**Comment by kelson42** [comment]
@veloman-yunkan Looks better now after a new publishing attempt, unfortunqtely we have still errors on Linux, see https://github.com/kiwix/kiwix-build/actions/runs/12360372427

**Comment by kelson42** [comment]
> * In addition the windows ZIP file has somehow a bad filename (is `kiwix-desktop_windows_x64_2.4.zip` but should be ``kiwix-desktop_windows_x64_2.4.0.zip`)

I believe to have fixed this point with https://github.com/kiwix/kiwix-build/commit/b1b545a65b416802d04bd5774fef5435b57afb68

**Comment by veloman-yunkan** [comment]
> * On linux job fails, not sure what was the output... pu whatbisnsure is that the source tarball is notmvisible at http://download.kiwix.org/release/kiwix-desktop/?C=M;O=D

Should be fixed by #787

**Comment by veloman-yunkan** [comment]
> * The flatpak repository upload fails, it seems we have the wrong credentials... might be a problem we already had, can not say for the moment.

This is currently outside my reach.

**Comment by veloman-yunkan** [comment]
> > * In addition the windows ZIP file has somehow a bad filename (is `kiwix-desktop_windows_x64_2.4.zip` but should be ``kiwix-desktop_windows_x64_2.4.0.zip`)
> 
> I believe to have fixed this point with [b1b545a](https://github.com/kiwix/kiwix-build/commit/b1b545a65b416802d04bd5774fef5435b57afb68)

The fix was [wrong](https://github.com/kiwix/kiwix-build/actions/runs/12368720008/job/34532666235):

>     --- creating desktop image ---
>     Traceback (most recent call last):
>       File "D:\a\kiwix-build\kiwix-build\.github\scripts\build_projects.py", line 18, in <module>
>         archive = create_desktop_image(make_release=False)
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>       File "D:\a\kiwix-build\kiwix-build\.github\scripts\common.py", line 547, in create_desktop_image
>         build_path = working_dir + ".zip"
>                      ~~~~~~~~~~~~^~~~~~~~
>     TypeError: unsupported operand type(s) for +: 'WindowsPath' and 'str'
>     Error: Process completed with exit code 1.


I corrected it with the second commit in #787.

**Comment by kelson42** [comment]
> > * The flatpak repository upload fails, it seems we have the wrong credentials... might be a problem we already had, can not say for the moment.
> 
> This is currently outside my reach.

The idea would be to upload this via KiwixBot, this has been long dine that way, but for some reason has stopped to work a few releases ago. We shoukd not rely on someone doing this manually... we see right now the problem of this approach. Do you have some kind of credential issue?

**Comment by veloman-yunkan** [comment]
> Do you have some kind of credential issue?

I don't think I have such an issue. So far I simply haven't dealt with Kiwix organization's credentials in any way (and I believe that I have no access to those).

**Comment by kelson42** [comment]
@veloman-yunkan They are in the GitHub secrets. Do you want to have them to test locally or is the current situation good enough?

**Comment by veloman-yunkan** [comment]
> They are in the GitHub secrets.

@kelson42 I don't have access to GitHub secrets (or any settings at all) for this repository.

**Comment by kelson42** [comment]
> > They are in the GitHub secrets.
> 
> [@kelson42](https://github.com/kelson42) I don't have access to GitHub secrets (or any settings at all) for this repository.

You are now `admin` of this repository... but secrets been secrets you can only modify them, not read them in GitHub.

**Comment by kelson42** [comment]
Regarding this last Flathub update:
* Flathub rebuilds itself from our source
* They manage a packaging repo at https://github.com/flathub/org.kiwix.desktop
* To make a new release we should do a new PR, which then is merge and then flathub repo is updated
* If we look at https://github.com/flathub/org.kiwix.desktop/commits/master/, `KiwixBot` has made many updates already.
* The whole logic to make the PR is in `scripts/common.py`
* We seems to have now - at least - a credentials problem, see https://github.com/kiwix/kiwix-build/actions/runs/12360372427/job/34495173566#step:6:66

@veloman-yunkan I will send you the credentials and hope you can have a look. Maybe you can try manuall to make `2.4.0` from the script and if OK we can make a full release of `2.4.1`.

**Comment by kelson42** [comment]
The problem of credentials has been solved by @rgaudin, but now we have a problem with compilation, see https://buildbot.flathub.org/#/builders/9/builds/15859

**Comment by kelson42** [comment]
@veloman-yunkan Finalement I believe [#793](https://github.com/kiwix/kiwix-build/pull/793) fixes the publishing on Flathub... so I will close this issue and prepare  `2.4.1` release to verify everything works fine now.
