### ISSUE TITLE
 No module named 'PIL' when building apk

### ISSUE THREAD

**Issue by tim-moody** [kiwix/kiwix-build#79]
on ubuntu 16.4 VM

install dependencies with following script
```
#!/usr/bin/env bash
# Python3, pip3, ninja
apt-get install python3-pip virtualenv && virtualenv -p python3 ./ && source ./bin/activate && pip3 install meson && hash -r && git clone git://github.com/ninja-build/ninja.git && cd ninja && git checkout release && ./configure.py --bootstrap && mkdir -p ../bin && cp ninja ../bin && cd .. && source ./bin/activate
```

clone

https://github.com/nataren/kiwix-build
https://github.com/nataren/kiwix-android-custom

(differ only in that embed_zim is true)

run

`python ./kiwix-build.py --verbose --target-platform android_arm --android-custom-app wikimedar kiwix-android-custom --zim-file-url https://download.kiwix.org/zim/wikipedia/wikipedia_ar_medicine_2017-08.zim`

result:

`Installing /opt/cesar-build/kiwix-build/BUILD_android_arm/kiwix-lib/kiwix.pc to /opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib/x86_64-linux-gnu/pkgconfig
OK
build kiwix-android :
SKIP
build kiwix-android-custom :
  configure kiwix-android-custom : run command './gen-custom-android-directory.py wikimedar --output-dir /opt/cesar-build/kiwix-build/BUILD_android_arm/kiwix-android-custom_wikimedar/custom/wikimedar'
current directory is '/opt/cesar-build/kiwix-build/SOURCE/kiwix-android-custom'
env is :
  CXX : '/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/bin/arm-linux-androideabi-g++'
  PS1 : '(cesar-build) \\[\\e]0;\\u@\\h: \\w\\a\\]${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ '
  CXXFLAGS : '-fPIC -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 --sysroot=/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/sysroot '
  PATH : '/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/bin:/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/bin:/usr/lib/ccache:/opt/cesar-build/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
  LESSCLOSE : '/usr/bin/lesspipe %s %s'
  PWD : '/opt/cesar-build/kiwix-build'
  SSH_TTY : '/dev/pts/0'
  HOME : '/root'
  PKG_CONFIG_PATH : ':/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib/x86_64-linux-gnu/pkgconfig'
  SSH_CONNECTION : '192.168.0.56 60203 10.100.0.9 22'
  MAIL : '/var/mail/root'
  SHELL : '/bin/bash'
  SSH_CLIENT : '192.168.0.56 60203 22'
  LD_LIBRARY_PATH : ':/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib:/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib64'
  SHLVL : '1'
  TERM : 'xterm'
  OLDPWD : '/opt/cesar-build'
  LOGNAME : 'root'
  CC : '/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/bin/arm-linux-androideabi-gcc'
  XDG_SESSION_ID : '49'
  CFLAGS : '-fPIC -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 --sysroot=/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/sysroot '
  USER : 'root'
  LESSOPEN : '| /usr/bin/lesspipe %s'
  LDFLAGS : '-L/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib -L/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/lib64 --sysroot=/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/sysroot '
  VIRTUAL_ENV : '/opt/cesar-build'
  NDK_DEBUG : '0'
  XDG_RUNTIME_DIR : '/run/user/0'
  LS_COLORS : 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'
  LANG : 'en_US.UTF-8'
  _ : '/opt/cesar-build/bin/python'
  ANDROID_HOME : '/opt/cesar-build/kiwix-build/TOOLCHAINS/android-sdk-r25.2.3'
  PKG_CONFIG_LIBDIR : '/opt/cesar-build/kiwix-build/BUILD_android_arm/android-ndk-r13b-arm-14/sysroot/lib/pkgconfig'
  CPPFLAGS : '-I/opt/cesar-build/kiwix-build/BUILD_android_arm/INSTALL/include '
Traceback (most recent call last):
  File "./gen-custom-android-directory.py", line 28, in <module>
    from PIL import Image
ImportError: No module named 'PIL'
ERROR
Stopping build due to errors
`

**Comment by kelson42** [comment]
I confirm that bug.

**Comment by mgautierfr** [comment]
Yes, but Pillow is only use by the script in `kiwix-android-custom` to generate the icons.
We should make kiwix-build detect and install dependencies of sub-project.

**Comment by kelson42** [comment]
Kiwix Android (custom apps) are not build anymore from kiwix-build. This bug won't be fixed.
