### ISSUE TITLE
macOS: error encountered while building uuid

### ISSUE THREAD

**Issue by automactic** [kiwix/kiwix-build#9]
Here is the log

[uuid_error.txt](https://github.com/kiwix/kiwix-build/files/771608/uuid_error.txt)

**Comment by mgautierfr** [comment]
This is a bug in e2fsprogs (uuid).
The `quota_inode_truncate` use a simple `return` to quit the function but it should return `errcode_t`.
On linux, gcc print a warning but the default compiler on macOS (clang ? gcc ?) see it as an error (which it is).

We use a pretty old version of e2fsprogs (1.42). This bug is fixed in recent version (since 1.42.5). The last version of e2fsprogs at this time is 1.43.4.

We should move to the last version.

**Comment by automactic** [comment]
The default compiler on macOS now is clang

**Comment by mgautierfr** [comment]
This last commit should fix this problem.
You may want to remove the old `uuid-1.42` in `ARCHIVE`, `SOURCE` and `BUILD_native_static` but is not necessary. Just relaunch the `kiwix-build.py` with same arguments.

**Comment by automactic** [comment]
I just re-runed the same command, but I got SSL cert error while re-downloading uuid

**Comment by automactic** [comment]
I removed everything related to `uuid-1.42`. I still got ssl error. Here's the log:
[uuid_ssl_error.txt](https://github.com/kiwix/kiwix-build/files/771764/uuid_ssl_error.txt)

**Comment by mgautierfr** [comment]
Hum, that's strange, I don't have this error.
Are you behind a proxy ? Or something that could "man in the middle" your connection to `https://www.kernel.org` ?

(I've just push a new version about the uuid, I had forget to change the uuid version. But it should not be relevant to your ssl error)

**Comment by automactic** [comment]
I have no idea why. Even doing
```
import urllib.request
response = urllib.request.urlopen('https://www.google.com')
```
results in the same ssl error. I will try again later when I got home.

**Comment by automactic** [comment]
I cannot solve it successfully. Based on a quick google search, I think I am not alone in these kind of problem (macOS + urllib + cert issue)

I am able to use the following code to bypass cert verify
```
import ssl
import urllib 
context = ssl.create_default_context()
context.check_hostname = False
context.verify_mode = ssl.CERT_NONE
response = urllib.request.urlopen('https://www.google.com', context=context)
```

**Comment by kelson42** [comment]
I think we need here a --no-cert-check option to the script.

**Comment by automactic** [comment]
Now I am able to download successfully. But I am encountering further errors when build. 
[uuid_log.txt](https://github.com/kiwix/kiwix-build/files/812109/uuid_log.txt)
But I checked `gettext` exists in `/usr/local/opt`

**Comment by automactic** [comment]
@mgautierfr, I think there needs to be a way to set our own compiler, flags, etc. 

When I cross build on macOS targeting iOS (`host=arm-apple-darwin`), I use `-isysroot $SDKROOT`

**Comment by mgautierfr** [comment]
@automactic please has a look on the pr #14 I've just created.
It introduce the concept of toolschain. You should be able to use it to set the right compiler and compiler flags.

**Comment by automactic** [comment]
@mgautierfr & @kelson42. Thanks for the update.
I created branch `apple-platforms` to add apple related stuff to build script. I was trying to build on macOS natively, had the following error.
[log.txt](https://github.com/kiwix/kiwix-build/files/817992/log.txt)

**Comment by mgautierfr** [comment]
@automactic 
Can you push your branch on github ? Even better, create a PR, then we will able to comment your change.
For what I see, clang cannot found librt. The flag `-lr` comes from the xapian pkg-config if the configure detect (and found) the `timer_create` function. This part was a bit buggy and I fix it with the e6673e2.
Try to remove all xapian and kiwix-tools stuff (SOURCE and BUILD) and launch a new compilation.
If it doesn't work, you will have to fix xapian (first find if you really need librt, and then find either why xapian add it or why kiwix-tools cannot found it)

Please open a new issue for this problem. This one is related to uuid and the `--no_cert_check`, and I would like to avoid to change the subject.

**Comment by automactic** [comment]
I merged e6673e20a50e20a2f1475584b019ea435cec05f4 into branch `apple-platforms`, remove SOURCE and BUILD dir, rebuild, got error
```
[BUILD]
build xapian-core :
  build_platform xapian-core : ERROR
Traceback (most recent call last):
  File "kiwix-build.py", line 988, in <module>
    builder.run()
  File "kiwix-build.py", line 965, in run
    self.build()
  File "kiwix-build.py", line 955, in build
    builder.build()
  File "kiwix-build.py", line 882, in build
    self.command('build_platform', self._build_platform)
  File "/Volumes/Data/Developer/kiwix-build/dependency_utils.py", line 172, in command
    return self.target.command(*args, **kwargs)
  File "/Volumes/Data/Developer/kiwix-build/dependency_utils.py", line 49, in command
    ret = function(*args, context=context)
  File "kiwix-build.py", line 851, in _build_platform
    context.try_skip(self.build_path)
  File "/Volumes/Data/Developer/kiwix-build/dependency_utils.py", line 169, in build_path
    return pj(self.buildEnv.build_dir, self.target.full_name)
  File "kiwix-build.py", line 829, in full_name
    arch = self.arch,
AttributeError: 'Xapian' object has no attribute 'arch'
```

**Comment by automactic** [comment]
I have already pushed by branch, it's called `apple-platforms`. I am also not sure I should create pull request based on which branch, since `apple-platforms` contains changes from `feature--no_cert_check` & `xapian-version`

**Comment by automactic** [comment]
Also on in kiwix-build.py, `class MesonBuilder(Builder)`, in function `_configure`, I don't believe you have imported `shutil`

**Comment by mgautierfr** [comment]
Do not try to merge the `xapian-version` branch into `apple-platform`. This is not related to your problem. 
Moreover, all the last problems you've got are related to your merge. On the `android` branch, `Builder`s have been moved into `depency_utils. py` and depency definitions into `dependencies. py`. Once the `xapian-version` branch is validated I will merge it into `master` and rebase `android` onto the new head.

**Comment by automactic** [comment]
Oh, sorry I misunderstood. I assumed you wanted to merge your fix then restart the build.

**Comment by automactic** [comment]
@mgautierfr, when building uuid on macOS natively. I need to provide path to `gettext`.
The log which contains the error is here: [uuid_log.txt](https://github.com/kiwix/kiwix-build/files/812109/uuid_log.txt)

**Comment by mgautierfr** [comment]
Hum, this seems surprising :
- The uuid configure seems to have passed but not the compilation step. If `libintl.h` cannot be found, the configure script should have failed (It can also be a bug if uuid) Can you give me the configure log also ?
And even better, can you be sure that the configure step and the compilation step are  up to date by deleting the uuid directory in `BUILD_native_dyn` and relaunch `kiwix-build.py` ?
- The `gettext` functionality is used by a lot of our dependencies (if not all). This problem should occur for all other projects (but maybe exporting the `CPATH` and `LIBRARY_PATH` hide the problem for other dependencies)

Also, If we need the gettext "package" on macos, we should add it to the list of needed packages.

And finally, if this is confirmed, we may indeed need a way to add specific options depending of which system we are building on (on not based on the system we are building for). But in this case, we may better merge the concept of toolchains and the `CROSS_ENV` variable and have a common and unique way of set global compilation options.

**Comment by automactic** [comment]
uuid now builds correctly
